const DEFAULT_POLICY={enabled:true,allowLiveExecution:false,maxRiskPerTradePct:1,minRewardRiskRatio:2,maxChasePct:1.5,maxPriceAgeSeconds:120,minConfirmationSources:2};
let policy=JSON.parse(localStorage.getItem('pai_policy')||'null')||{...DEFAULT_POLICY};
let portfolio=JSON.parse(localStorage.getItem('pai_portfolio')||'[]');
let evaluations=Number(localStorage.getItem('pai_evaluations')||'0');
let liveState={connected:false,lastEvent:null,prices:{},news:[],holdings:[],positions:[],orders:[]};
let liveSocket=null,reconnectTimer=null;

const $=id=>document.getElementById(id),num=id=>Number($(id).value),checked=id=>$(id).checked;
document.querySelectorAll('.nav button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));btn.classList.add('active');$(btn.dataset.section).classList.add('active')}));
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n||0);
const backendHttp=()=>`${location.protocol==='https:'?'https':'http'}://${location.hostname||'127.0.0.1'}:8000`;
const backendWs=()=>`${location.protocol==='https:'?'wss':'ws'}://${location.hostname||'127.0.0.1'}:8000/ws/live`;

function latestPrice(symbol){const key=Object.keys(liveState.prices).find(k=>k.endsWith(`:${symbol}`)||k===symbol);const event=key?liveState.prices[key]:null;return event?.ltp??event?.price??event?.last_price??null}
function renderDashboard(){const source=liveState.holdings.length?liveState.holdings:portfolio;const value=source.reduce((s,p)=>{const symbol=p.trading_symbol||p.symbol||p.tradingsymbol||'';const qty=Number(p.quantity??p.qty??0);const avg=Number(p.average_price??p.avg??p.averagePrice??0);const lp=latestPrice(symbol);return s+qty*(Number(lp)||avg)},0);$('kpiPortfolio').textContent=money(value);$('kpiPositions').textContent=(liveState.positions.length||source.length);$('kpiEvaluations').textContent=evaluations;$('dashboardPositions').innerHTML=source.length?source.slice(-8).reverse().map(p=>{const symbol=p.trading_symbol||p.symbol||p.tradingsymbol||'';const market=p.exchange||p.market||'NSE';const qty=Number(p.quantity??p.qty??0);const avg=Number(p.average_price??p.avg??p.averagePrice??0);const lp=latestPrice(symbol);return `<tr><td>${symbol}</td><td>${market}</td><td>${qty}</td><td>${avg||'—'}</td><td>${lp?money(qty*lp):money(qty*avg)}</td></tr>`}).join(''):'<tr><td colspan="5" class="muted">No positions saved.</td></tr>';renderLiveStatus()}
function renderPortfolio(){$('portfolioRows').innerHTML=portfolio.length?portfolio.map((p,i)=>`<tr><td>${p.symbol}</td><td>${p.market}</td><td>${p.qty}</td><td>${p.avg}</td><td>${money(p.qty*(latestPrice(p.symbol)||p.avg))}</td><td><button class="secondary" onclick="removePosition(${i})">Remove</button></td></tr>`).join(''):'<tr><td colspan="6" class="muted">No positions saved.</td></tr>';renderDashboard()}
function renderLiveStatus(){const status=$('liveStatus');if(!status)return;status.className=liveState.connected?'safe':'warn';status.innerHTML=`<b>${liveState.connected?'Live stream connected':'Live stream disconnected'}</b><br>${liveState.lastEvent?`Last event: ${new Date(liveState.lastEvent).toLocaleTimeString()}`:'Waiting for backend events.'}`}
function renderNews(){const box=$('liveNews');if(!box)return;box.innerHTML=liveState.news.length?liveState.news.slice(0,12).map(n=>`<div class="broker"><div><b>${n.title||'Headline'}</b><div class="muted">${n.source||''}${n.published?` · ${n.published}`:''}</div></div></div>`).join(''):'<div class="muted">Waiting for news updates.</div>'}

function addPosition(){const p={symbol:$('pSymbol').value.trim().toUpperCase(),market:$('pMarket').value,qty:num('pQty'),avg:num('pAvg')};if(!p.symbol||!(p.qty>0)||!(p.avg>0)){alert('Enter a valid symbol, quantity and average price.');return}portfolio.push(p);localStorage.setItem('pai_portfolio',JSON.stringify(portfolio));$('pSymbol').value='';$('pQty').value='';$('pAvg').value='';renderPortfolio()}
function removePosition(i){portfolio.splice(i,1);localStorage.setItem('pai_portfolio',JSON.stringify(portfolio));renderPortfolio()}

function evaluateTrade(){const direction=$('direction').value,current=num('currentPrice'),reference=num('referencePrice'),entry=num('entryPrice'),stop=num('stopLoss'),target=num('targetPrice'),qty=num('quantity'),capital=num('portfolioValue'),quoteAge=num('quoteAge'),sources=num('sourceCount');const reasons=[];if(!$('symbol').value.trim())reasons.push('Symbol is required.');if(quoteAge>policy.maxPriceAgeSeconds)reasons.push(`Quote is stale (${quoteAge}s; maximum ${policy.maxPriceAgeSeconds}s).`);if(sources<policy.minConfirmationSources)reasons.push(`Insufficient confirmation sources (${sources}; minimum ${policy.minConfirmationSources}).`);const missing=[];if(!checked('newsChecked'))missing.push('news');if(!checked('technicalChecked'))missing.push('technical');if(!checked('portfolioChecked'))missing.push('portfolio');if(missing.length)reasons.push('Missing confirmations: '+missing.join(', ')+'.');let risk=0,reward=0;if(direction==='long'){if(!(stop<entry&&entry<target))reasons.push('Long setup must satisfy stop loss < entry < target.');risk=entry-stop;reward=target-entry}else{if(!(target<entry&&entry<stop))reasons.push('Short setup must satisfy target < entry < stop loss.');risk=stop-entry;reward=entry-target}const rr=risk>0&&reward>0?reward/risk:0;if(rr<policy.minRewardRiskRatio)reasons.push(`Reward/risk ${rr.toFixed(2)} is below minimum ${policy.minRewardRiskRatio.toFixed(2)}.`);const positionRisk=Math.max(0,risk)*Math.max(0,qty);const riskPct=capital>0?positionRisk/capital*100:0;if(riskPct>policy.maxRiskPerTradePct)reasons.push(`Position risks ${riskPct.toFixed(2)}% of portfolio; maximum ${policy.maxRiskPerTradePct.toFixed(2)}%.`);let chase=0;if(reference>0){chase=direction==='long'?(current-reference)/reference*100:(reference-current)/reference*100;if(chase>policy.maxChasePct)reasons.push(`Do not chase: ${chase.toFixed(2)}% beyond reference; maximum ${policy.maxChasePct.toFixed(2)}%.`)}if(checked('liveRequested')&&!policy.allowLiveExecution)reasons.push('Live execution is not enabled in policy.');evaluations++;localStorage.setItem('pai_evaluations',String(evaluations));renderDashboard();const eligible=!reasons.length,action=eligible?(direction==='long'?'BUY':'SELL'):'WAIT';$('decisionBox').className='decision '+(eligible?'good':'wait');$('decisionBox').querySelector('strong').textContent=action;$('decisionText').textContent=eligible?'Setup passes the configured guardrails.':'Setup does not pass the configured guardrails.';$('rr').textContent=rr.toFixed(2);$('riskPct').textContent=riskPct.toFixed(3)+'%';$('chasePct').textContent=chase.toFixed(3)+'%';$('positionRisk').textContent=positionRisk.toFixed(2);$('reasons').innerHTML='';(eligible?['All configured guardrails passed.','Revalidate live market conditions immediately before any real trade.']:reasons).forEach(r=>{const li=document.createElement('li');li.textContent=r;$('reasons').appendChild(li)})}
function setValues(v){Object.entries(v).forEach(([k,val])=>$(k).value=val)}
function loadValid(){setValues({symbol:'RELIANCE',market:'NSE',direction:'long',currentPrice:101,referencePrice:100,entryPrice:101,stopLoss:99,targetPrice:105,quantity:10,portfolioValue:100000,quoteAge:0,sourceCount:2});['newsChecked','technicalChecked','portfolioChecked'].forEach(id=>$(id).checked=true);$('liveRequested').checked=false;evaluateTrade()}
function loadRejected(){setValues({symbol:'TEST',market:'NSE',direction:'long',currentPrice:104,referencePrice:100,entryPrice:104,stopLoss:99,targetPrice:108,quantity:500,portfolioValue:100000,quoteAge:180,sourceCount:1});$('newsChecked').checked=false;$('technicalChecked').checked=true;$('portfolioChecked').checked=true;$('liveRequested').checked=true;evaluateTrade()}

const brokers=['Groww','Zerodha / Kite','Interactive Brokers','Other broker'];$('brokerCards').innerHTML=brokers.map(b=>`<div class="broker"><div><b>${b}</b><div class="muted">${b==='Groww'?'Backend integration prepared':'Not connected'}</div></div><button class="secondary" onclick="showBrokerInfo('${b.replaceAll("'","\\'")}')">Connection info</button></div>`).join('');
function showBrokerInfo(name){$('brokerInfo').innerHTML=`<b>${name}</b><br>Use only the broker's official API. Secrets remain in backend/.env and are never stored in this page.`}
function loadSettings(){$('sRisk').value=policy.maxRiskPerTradePct;$('sRR').value=policy.minRewardRiskRatio;$('sChase').value=policy.maxChasePct;$('sQuoteAge').value=policy.maxPriceAgeSeconds;$('sSources').value=policy.minConfirmationSources}
function saveSettings(){policy.maxRiskPerTradePct=num('sRisk');policy.minRewardRiskRatio=num('sRR');policy.maxChasePct=num('sChase');policy.maxPriceAgeSeconds=num('sQuoteAge');policy.minConfirmationSources=num('sSources');localStorage.setItem('pai_policy',JSON.stringify(policy));alert('Settings saved locally in this browser.')}
function clearLocalData(){if(confirm('Clear all locally saved portfolio and settings data?')){localStorage.removeItem('pai_policy');localStorage.removeItem('pai_portfolio');localStorage.removeItem('pai_evaluations');location.reload()}}

async function hydrateLiveState(){try{const r=await fetch(`${backendHttp()}/api/live/state`);if(!r.ok)return;const s=await r.json();liveState={...liveState,...s};renderPortfolio();renderNews()}catch(_){}}
function handleLiveEvent(msg){liveState.lastEvent=msg.ts||new Date().toISOString();if(msg.type==='market'){const d=msg.data||{};const symbol=d.trading_symbol||d.symbol||d.tradingsymbol;const exchange=d.exchange||'NSE';if(symbol)liveState.prices[`${exchange}:${symbol}`]=d;const active=$('symbol')?.value.trim().toUpperCase();if(active&&symbol===active){const p=Number(d.ltp??d.price??d.last_price);if(p>0){$('currentPrice').value=p;$('quoteAge').value=0}}}else if(msg.type==='portfolio'){liveState.holdings=msg.holdings||liveState.holdings;liveState.positions=msg.positions||liveState.positions}else if(msg.type==='order'){liveState.orders.unshift(msg.data)}else if(msg.type==='news'){liveState.news=msg.items||[]}renderPortfolio();renderNews()}
function connectLive(){clearTimeout(reconnectTimer);try{liveSocket=new WebSocket(backendWs());liveSocket.onopen=()=>{liveState.connected=true;renderLiveStatus();hydrateLiveState()};liveSocket.onmessage=e=>{try{handleLiveEvent(JSON.parse(e.data))}catch(_){}};liveSocket.onerror=()=>liveSocket.close();liveSocket.onclose=()=>{liveState.connected=false;renderLiveStatus();reconnectTimer=setTimeout(connectLive,1500)}}catch(_){reconnectTimer=setTimeout(connectLive,1500)}}

renderPortfolio();loadSettings();loadValid();renderNews();connectLive();