const DEFAULT_POLICY={enabled:true,allowLiveExecution:false,maxRiskPerTradePct:1,minRewardRiskRatio:2,maxChasePct:1.5,maxPriceAgeSeconds:120,minConfirmationSources:2};
let policy=JSON.parse(localStorage.getItem('pai_policy')||'null')||{...DEFAULT_POLICY};
let portfolio=JSON.parse(localStorage.getItem('pai_portfolio')||'[]');
let evaluations=Number(localStorage.getItem('pai_evaluations')||'0');

const $=id=>document.getElementById(id),num=id=>Number($(id).value),checked=id=>$(id).checked;
document.querySelectorAll('.nav button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));btn.classList.add('active');$(btn.dataset.section).classList.add('active')}));
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n||0);

function renderDashboard(){const value=portfolio.reduce((s,p)=>s+p.qty*p.avg,0);$('kpiPortfolio').textContent=money(value);$('kpiPositions').textContent=portfolio.length;$('kpiEvaluations').textContent=evaluations;$('dashboardPositions').innerHTML=portfolio.length?portfolio.slice(-6).reverse().map(p=>`<tr><td>${p.symbol}</td><td>${p.market}</td><td>${p.qty}</td><td>${p.avg}</td><td>${money(p.qty*p.avg)}</td></tr>`).join(''):'<tr><td colspan="5" class="muted">No positions saved.</td></tr>'}
function renderPortfolio(){$('portfolioRows').innerHTML=portfolio.length?portfolio.map((p,i)=>`<tr><td>${p.symbol}</td><td>${p.market}</td><td>${p.qty}</td><td>${p.avg}</td><td>${money(p.qty*p.avg)}</td><td><button class="secondary" onclick="removePosition(${i})">Remove</button></td></tr>`).join(''):'<tr><td colspan="6" class="muted">No positions saved.</td></tr>';renderDashboard()}
function addPosition(){const p={symbol:$('pSymbol').value.trim().toUpperCase(),market:$('pMarket').value,qty:num('pQty'),avg:num('pAvg')};if(!p.symbol||!(p.qty>0)||!(p.avg>0)){alert('Enter a valid symbol, quantity and average price.');return}portfolio.push(p);localStorage.setItem('pai_portfolio',JSON.stringify(portfolio));$('pSymbol').value='';$('pQty').value='';$('pAvg').value='';renderPortfolio()}
function removePosition(i){portfolio.splice(i,1);localStorage.setItem('pai_portfolio',JSON.stringify(portfolio));renderPortfolio()}

function evaluateTrade(){const direction=$('direction').value,current=num('currentPrice'),reference=num('referencePrice'),entry=num('entryPrice'),stop=num('stopLoss'),target=num('targetPrice'),qty=num('quantity'),capital=num('portfolioValue'),quoteAge=num('quoteAge'),sources=num('sourceCount');const reasons=[];if(!$('symbol').value.trim())reasons.push('Symbol is required.');if(quoteAge>policy.maxPriceAgeSeconds)reasons.push(`Quote is stale (${quoteAge}s; maximum ${policy.maxPriceAgeSeconds}s).`);if(sources<policy.minConfirmationSources)reasons.push(`Insufficient confirmation sources (${sources}; minimum ${policy.minConfirmationSources}).`);const missing=[];if(!checked('newsChecked'))missing.push('news');if(!checked('technicalChecked'))missing.push('technical');if(!checked('portfolioChecked'))missing.push('portfolio');if(missing.length)reasons.push('Missing confirmations: '+missing.join(', ')+'.');let risk=0,reward=0;if(direction==='long'){if(!(stop<entry&&entry<target))reasons.push('Long setup must satisfy stop loss < entry < target.');risk=entry-stop;reward=target-entry}else{if(!(target<entry&&entry<stop))reasons.push('Short setup must satisfy target < entry < stop loss.');risk=stop-entry;reward=entry-target}const rr=risk>0&&reward>0?reward/risk:0;if(rr<policy.minRewardRiskRatio)reasons.push(`Reward/risk ${rr.toFixed(2)} is below minimum ${policy.minRewardRiskRatio.toFixed(2)}.`);const positionRisk=Math.max(0,risk)*Math.max(0,qty);const riskPct=capital>0?positionRisk/capital*100:0;if(riskPct>policy.maxRiskPerTradePct)reasons.push(`Position risks ${riskPct.toFixed(2)}% of portfolio; maximum ${policy.maxRiskPerTradePct.toFixed(2)}%.`);let chase=0;if(reference>0){chase=direction==='long'?(current-reference)/reference*100:(reference-current)/reference*100;if(chase>policy.maxChasePct)reasons.push(`Do not chase: ${chase.toFixed(2)}% beyond reference; maximum ${policy.maxChasePct.toFixed(2)}%.`)}if(checked('liveRequested'))reasons.push('Live execution is disabled in this private prototype.');evaluations++;localStorage.setItem('pai_evaluations',String(evaluations));renderDashboard();const eligible=!reasons.length,action=eligible?(direction==='long'?'BUY':'SELL'):'WAIT';$('decisionBox').className='decision '+(eligible?'good':'wait');$('decisionBox').querySelector('strong').textContent=action;$('decisionText').textContent=eligible?'Setup passes the configured guardrails in paper mode.':'Setup does not pass the configured guardrails.';$('rr').textContent=rr.toFixed(2);$('riskPct').textContent=riskPct.toFixed(3)+'%';$('chasePct').textContent=chase.toFixed(3)+'%';$('positionRisk').textContent=positionRisk.toFixed(2);$('reasons').innerHTML='';(eligible?['All configured guardrails passed.','Execution remains paper-only.','Revalidate live price and market conditions immediately before any real trade.']:reasons).forEach(r=>{const li=document.createElement('li');li.textContent=r;$('reasons').appendChild(li)})}
function setValues(v){Object.entries(v).forEach(([k,val])=>$(k).value=val)}
function loadValid(){setValues({symbol:'AAPL',market:'NASDAQ',direction:'long',currentPrice:101,referencePrice:100,entryPrice:101,stopLoss:99,targetPrice:105,quantity:10,portfolioValue:100000,quoteAge:30,sourceCount:2});['newsChecked','technicalChecked','portfolioChecked'].forEach(id=>$(id).checked=true);$('liveRequested').checked=false;evaluateTrade()}
function loadRejected(){setValues({symbol:'TEST',market:'NSE',direction:'long',currentPrice:104,referencePrice:100,entryPrice:104,stopLoss:99,targetPrice:108,quantity:500,portfolioValue:100000,quoteAge:180,sourceCount:1});$('newsChecked').checked=false;$('technicalChecked').checked=true;$('portfolioChecked').checked=true;$('liveRequested').checked=true;evaluateTrade()}

const brokers=['Zerodha / Kite','Groww','Interactive Brokers','Other broker'];$('brokerCards').innerHTML=brokers.map(b=>`<div class="broker"><div><b>${b}</b><div class="muted">Not connected</div></div><button class="secondary" onclick="showBrokerInfo('${b.replaceAll("'","\\'")}')">Prepare connection</button></div>`).join('');
function showBrokerInfo(name){$('brokerInfo').innerHTML=`<b>${name}</b><br>Use the broker's official API or OAuth flow. Do not paste a password, OTP, PIN, TOTP seed, recovery code, or withdrawal-enabled secret into this page.`}
function loadSettings(){$('sRisk').value=policy.maxRiskPerTradePct;$('sRR').value=policy.minRewardRiskRatio;$('sChase').value=policy.maxChasePct;$('sQuoteAge').value=policy.maxPriceAgeSeconds;$('sSources').value=policy.minConfirmationSources}
function saveSettings(){policy.maxRiskPerTradePct=num('sRisk');policy.minRewardRiskRatio=num('sRR');policy.maxChasePct=num('sChase');policy.maxPriceAgeSeconds=num('sQuoteAge');policy.minConfirmationSources=num('sSources');localStorage.setItem('pai_policy',JSON.stringify(policy));alert('Settings saved locally in this browser.')}
function clearLocalData(){if(confirm('Clear all locally saved portfolio and settings data?')){localStorage.removeItem('pai_policy');localStorage.removeItem('pai_portfolio');localStorage.removeItem('pai_evaluations');location.reload()}}

renderPortfolio();loadSettings();loadValid();
