#!/usr/bin/env bash
set -euo pipefail
cd nse-delivery-v170
python3 - <<'PY'
from pathlib import Path

p=Path('app/build.gradle');s=p.read_text();s=s.replace("versionCode 170","versionCode 180").replace("versionName '1.7.0'","versionName '1.8.0'");p.write_text(s)

p=Path('app/src/main/AndroidManifest.xml');s=p.read_text();s=s.replace('android:label="NSE Delivery Momentum"','android:label="NSE Intraday Momentum"').replace('User-requested continuous NSE cash-equity momentum monitoring and delivery-order execution','User-requested continuous NSE cash-equity intraday LONG and SHORT signal monitoring');p.write_text(s)

p=Path('app/src/main/java/com/suhas/nsedeliverymomentum/DeliveryMomentumService.java');s=p.read_text()
old='''        recordRecommendations(out);recordTrajectoryRecommendations(trajOut);recordBreakdownRecommendations(shortOut);\n        maybeAutoBuy(out);maybeAutoBuyTrajectory(trajOut); // Short engine is intentionally analysis-only; never CNC auto-buy.\n        broadcast();'''
new='''        recordRecommendations(out);recordTrajectoryRecommendations(trajOut);recordBreakdownRecommendations(shortOut);\n        // v1.8.0: all three engines are intraday signal engines. Execution is manual;\n        // confirmed LONG/SHORT calls are surfaced through actionable notifications.\n        broadcast();'''
assert old in s;s=s.replace(old,new)
old='''    private void recordRecommendations(List<Candidate> out){for(Candidate c:out){if(!"BUY".equals(c.state))continue;String k="rec_"+GrowwClient.sessionDay()+"_"+c.symbol;if(store.getBool(k,false))continue;store.putBool(k,true);learning.add(new LearningStore.Call(c.symbol,c.price,c.score,"LONG"));learning.noteCall();notifyCall("CONFIRMED DELIVERY BUY: "+c.symbol,"₹"+fmt(c.price)+" • score "+fmt(c.score)+" • confidence "+fmt(c.confidence)+" • projected +"+fmt(c.expected)+"%");}}\n    private void recordTrajectoryRecommendations(List<TrajectoryCandidate> out){for(TrajectoryCandidate c:out){if(!"UPTREND".equals(c.state))continue;String k="rec_"+GrowwClient.sessionDay()+"_"+c.symbol;if(store.getBool(k,false))continue;store.putBool(k,true);learning.add(new LearningStore.Call(c.symbol,c.price,c.score,"LONG"));learning.noteCall();notifyCall("CONFIRMED UPTREND BUY: "+c.symbol,"₹"+fmt(c.price)+" • score "+fmt(c.score)+" • pace "+fmt(c.pace)+"%/h");}}\n    private void recordBreakdownRecommendations(List<BreakdownCandidate> out){for(BreakdownCandidate c:out){if(!"SHORT".equals(c.state))continue;String k="short_rec_"+GrowwClient.sessionDay()+"_"+c.symbol;if(store.getBool(k,false))continue;store.putBool(k,true);learning.add(new LearningStore.Call(c.symbol,c.price,c.score,"SHORT"));learning.noteCall();notifyCall("CONFIRMED SHORT SETUP: "+c.symbol,"₹"+fmt(c.price)+" • score "+fmt(c.score)+" • drop "+fmt(c.drop)+"% • analysis only");}}'''
new='''    private void recordRecommendations(List<Candidate> out){\n        for(Candidate c:out){\n            if(!"BUY".equals(c.state))continue;\n            String k="rec_"+GrowwClient.sessionDay()+"_"+c.symbol;if(store.getBool(k,false))continue;\n            store.putBool(k,true);learning.add(new LearningStore.Call(c.symbol,c.price,c.score,"LONG"));learning.noteCall();\n            double targetPct=TargetMath.continuationPct(c.expected,c.confidence);double target=TargetMath.longTarget(c.price,targetPct);\n            notifySignal("LONG",c.symbol,c.price,target,targetPct,c.score,c.confidence,"Continuation confirmed");\n        }\n    }\n    private void recordTrajectoryRecommendations(List<TrajectoryCandidate> out){\n        for(TrajectoryCandidate c:out){\n            if(!"UPTREND".equals(c.state))continue;\n            String k="rec_"+GrowwClient.sessionDay()+"_"+c.symbol;if(store.getBool(k,false))continue;\n            store.putBool(k,true);learning.add(new LearningStore.Call(c.symbol,c.price,c.score,"LONG"));learning.noteCall();\n            double targetPct=TargetMath.trajectoryPct(c.pace,c.recent,c.confidence);double target=TargetMath.longTarget(c.price,targetPct);\n            notifySignal("LONG",c.symbol,c.price,target,targetPct,c.score,c.confidence,"Upward trajectory confirmed");\n        }\n    }\n    private void recordBreakdownRecommendations(List<BreakdownCandidate> out){\n        for(BreakdownCandidate c:out){\n            if(!"SHORT".equals(c.state))continue;\n            String k="short_rec_"+GrowwClient.sessionDay()+"_"+c.symbol;if(store.getBool(k,false))continue;\n            store.putBool(k,true);learning.add(new LearningStore.Call(c.symbol,c.price,c.score,"SHORT"));learning.noteCall();\n            double targetPct=TargetMath.shortPct(c.recentDrop,c.pace,c.recent,c.freshBreak,c.confidence);double target=TargetMath.shortTarget(c.price,targetPct);\n            notifySignal("SHORT",c.symbol,c.price,target,targetPct,c.score,c.confidence,"Falling-knife breakdown confirmed");\n        }\n    }'''
assert old in s;s=s.replace(old,new)
old='''    private Notification notification(String text){Intent x=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,1,x,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,"delivery_momentum").setSmallIcon(android.R.drawable.stat_notify_sync).setContentTitle("NSE Delivery Momentum").setContentText(text).setOngoing(true).setContentIntent(pi).build();}\n    private void notifyCall(String title,String text){((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify((int)(System.currentTimeMillis()%100000),new Notification.Builder(this,"delivery_momentum").setSmallIcon(android.R.drawable.stat_notify_more).setContentTitle(title).setContentText(text).setAutoCancel(true).build());}\n    private void createChannel(){if(Build.VERSION.SDK_INT>=26)((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(new NotificationChannel("delivery_momentum","Delivery Momentum",NotificationManager.IMPORTANCE_DEFAULT));}'''
new='''    private Notification notification(String text){Intent x=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,1,x,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,"intraday_scanner").setSmallIcon(android.R.drawable.stat_notify_sync).setContentTitle("NSE Intraday Scanner").setContentText(text).setOngoing(true).setContentIntent(pi).build();}\n    private void notifyCall(String title,String text){if(!store.getBool("alerts",true))return;Intent x=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,2,x,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Notification.Builder b=new Notification.Builder(this,"intraday_signals").setSmallIcon(android.R.drawable.stat_notify_more).setContentTitle(title).setContentText(text).setStyle(new Notification.BigTextStyle().bigText(text)).setContentIntent(pi).setAutoCancel(true).setCategory(Notification.CATEGORY_RECOMMENDATION).setVisibility(Notification.VISIBILITY_PUBLIC);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify((int)(System.currentTimeMillis()%100000),b.build());}\n    private void notifySignal(String side,String symbol,double entry,double target,double pct,double score,double confidence,String reason){String sign="SHORT".equals(side)?"-":"+";String title=side+" • "+symbol+" • CONFIRMED";String text="ENTRY ₹"+fmt(entry)+"  →  TARGET ₹"+fmt(target)+"  •  "+sign+fmt(pct)+"%  •  Score "+fmt(score)+"  •  Confidence "+fmt(confidence)+"%  •  "+reason;notifyCall(title,text);}\n    private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationManager n=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);n.createNotificationChannel(new NotificationChannel("intraday_scanner","Intraday Scanner Status",NotificationManager.IMPORTANCE_LOW));NotificationChannel sig=new NotificationChannel("intraday_signals","Confirmed Intraday LONG / SHORT Signals",NotificationManager.IMPORTANCE_HIGH);sig.enableVibration(true);sig.setDescription("Confirmed intraday entry and target alerts");n.createNotificationChannel(sig);}}'''
assert old in s;s=s.replace(old,new);p.write_text(s)

p=Path('app/src/main/java/com/suhas/nsedeliverymomentum/MainActivity.java');s=p.read_text()
s=s.replace('        store=new SecretStore(this);Housekeeping.runDaily(this,store);\n        getWindow().setStatusBarColor(bg);','        store=new SecretStore(this);Housekeeping.runDaily(this,store);\n        if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},180);\n        getWindow().setStatusBarColor(bg);')
s=s.replace('titles.addView(label("NSE DELIVERY MOMENTUM",22,text,true));','titles.addView(label("NSE INTRADAY MOMENTUM",22,text,true));')
s=s.replace('titles.addView(label("3-engine ALL-NSE scanner + NIGHT LAB + AUTO CLEANUP",12,muted,false));','titles.addView(label("3-engine INTRADAY scanner + NIGHT LAB + confirmed alerts",12,muted,false));')
s=s.replace('Three independent ALL-NSE engines plus off-market walk-forward learning. NIGHT LAB adapts validated score/persistence gates; housekeeping keeps detailed metadata bounded while lifetime learning survives.','Three independent intraday engines: two LONG engines and one SHORT engine. Confirmed signals include ENTRY and TARGET notifications. NIGHT LAB adapts validated score/persistence gates while housekeeping keeps learning storage bounded.')
s=s.replace('liveState=label("PAPER LEARNING",17,text,true);liveSub=label("Scanner learns only confirmed BUY/SHORT calls. No real orders.",12,muted,false);','liveState=label("CONFIRMED ALERTS",17,text,true);liveSub=label("Notifications fire only when a LONG or SHORT call reaches confirmed state.",12,muted,false);')
s=s.replace('live.setChecked(store.getBool("live",false));','live.setChecked(store.getBool("alerts",true));')
old='live.setOnCheckedChangeListener((b,c)->{if(c){if(!store.getBool("authenticated",false)||!store.getBool("ip_match",false)){b.setChecked(false);toast("Authenticate Groww and verify static IP first");return;}new AlertDialog.Builder(this).setTitle("Enable live delivery buying?").setMessage("Only CONFIRMED BUY calls can place REAL NSE CASH / CNC market BUY orders. SHORT signals are analysis-only and are never auto-executed.").setPositiveButton("ENABLE LIVE",(d,w)->{store.putBool("live",true);updateLiveCard();}).setNegativeButton("KEEP PAPER",(d,w)->b.setChecked(false)).show();}else{store.putBool("live",false);updateLiveCard();}});'
new='live.setOnCheckedChangeListener((b,c)->{store.putBool("alerts",c);updateLiveCard();if(c)toast("Confirmed LONG / SHORT notifications enabled");});'
assert old in s;s=s.replace(old,new)
s=s.replace('strategy.addView(label("Engine 1: continuation BUY • Engine 2: persistent-climb BUY • Engine 3: falling-knife SHORT",12,muted,false));','strategy.addView(label("Engine 1: continuation LONG • Engine 2: persistent-climb LONG • Engine 3: falling-knife SHORT • ALL INTRADAY",12,muted,false));')
s=s.replace('TextView foot=label("LIVE: CNC BUY ONLY  •  SHORT: ANALYSIS ONLY  •  STRICT MULTI-SCAN CONFIRMATION  •  NIGHT LAB WALK-FORWARD VALIDATION  •  NO FORCED QUOTA  •  NO AUTO-SELL",10,muted,true);','TextView foot=label("ALL 3 ENGINES: INTRADAY  •  LONG + LONG + SHORT  •  CONFIRMED ENTRY/TARGET ALERTS  •  STRICT MULTI-SCAN CONFIRMATION  •  NO AUTO-ORDER",10,muted,true);')
old='section(box,"LIVE BUY LIMITS","Applies only when LIVE EXECUTION is enabled.");EditText capital=field("Capital per delivery BUY (₹)",store.get("capital","10000"),false),max=field("Maximum live BUYs / day",String.valueOf(store.getInt("max_buys",10)),false);capital.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);max.setInputType(InputType.TYPE_CLASS_NUMBER);box.addView(capital);box.addView(max);'
new='section(box,"CONFIRMED SIGNAL ALERTS","All three engines are intraday. Engine 1 and 2 are LONG; Engine 3 is SHORT. Confirmed alerts show current entry and directional target price. No automatic order is sent in v1.8.0.");TextView alertState=label(store.getBool("alerts",true)?"Notifications: ENABLED":"Notifications: DISABLED",10,muted,false);alertState.setPadding(dp(10),dp(8),dp(10),dp(8));alertState.setBackground(round(surface2,dp(12),0,0));box.addView(alertState);'
assert old in s;s=s.replace(old,new)
s=s.replace('AlertDialog d=new AlertDialog.Builder(this).setTitle("Delivery Momentum Settings")','AlertDialog d=new AlertDialog.Builder(this).setTitle("Intraday Momentum Settings")')
old='d.setOnDismissListener(x->{store.put("capital",capital.getText().toString().trim().isEmpty()?"10000":capital.getText().toString().trim());try{store.putInt("max_buys",Math.max(1,Math.min(30,Integer.parseInt(max.getText().toString().trim()))));}catch(Exception ignored){store.putInt("max_buys",10);}updateHeaderState();});d.show();'
assert old in s;s=s.replace(old,'d.setOnDismissListener(x->{updateHeaderState();});d.show();')
old='private void updateLiveCard(){boolean on=store.getBool("live",false);if(live!=null&&live.isChecked()!=on)live.setChecked(on);if(liveState!=null){liveState.setText(on?"LIVE EXECUTION ON":"PAPER LEARNING");liveState.setTextColor(on?green:text);liveSub.setText(on?"Confirmed BUY calls may place real CNC orders. SHORT signals remain analysis-only. No auto-sell.":"Scanner learns only confirmed BUY/SHORT calls. No real orders.");}}'
new='private void updateLiveCard(){boolean on=store.getBool("alerts",true);if(live!=null&&live.isChecked()!=on)live.setChecked(on);if(liveState!=null){liveState.setText(on?"CONFIRMED ALERTS ON":"CONFIRMED ALERTS OFF");liveState.setTextColor(on?green:muted);liveSub.setText(on?"LONG/SHORT notifications include ENTRY and TARGET prices. No automatic order is sent.":"Scanner continues learning, but confirmed call notifications are muted.");}}'
assert old in s;s=s.replace(old,new);p.write_text(s)
PY
cat > app/src/main/java/com/suhas/nsedeliverymomentum/TargetMath.java <<'JAVA'
package com.suhas.nsedeliverymomentum;
/** Intraday target calculator. Targets are first model objectives, not guarantees. */
public final class TargetMath {
    private TargetMath(){}
    static double continuationPct(double expectedRemaining,double confidence){double confidenceScale=0.85+0.15*clamp(confidence/100.0,0,1);return clamp(Math.max(1.0,expectedRemaining*confidenceScale),1.0,4.0);}
    static double trajectoryPct(double hourlyPace,double recentPace,double confidence){double pace=Math.max(0,0.45*Math.max(0,recentPace)+0.35*Math.max(0,hourlyPace));double conf=0.40*clamp(confidence/100.0,0,1);return clamp(Math.max(1.0,pace+conf),1.0,3.0);}
    static double shortPct(double recentDrop,double hourlyPace,double recentPace,double freshBreakdown,double confidence){double momentum=0.45*Math.max(0,recentDrop)+0.25*Math.max(0,-recentPace)+0.15*Math.max(0,-hourlyPace)+0.15*Math.max(0,freshBreakdown);double conf=0.35*clamp(confidence/100.0,0,1);return clamp(Math.max(1.0,momentum+conf),1.0,3.5);}
    static double longTarget(double entry,double pct){return round2(entry*(1.0+pct/100.0));}
    static double shortTarget(double entry,double pct){return round2(entry*(1.0-pct/100.0));}
    private static double clamp(double x,double lo,double hi){return Math.max(lo,Math.min(hi,x));}
    private static double round2(double x){return Math.round(x*100.0)/100.0;}
}
JAVA
cat > app/src/test/java/com/suhas/nsedeliverymomentum/TargetMathTest.java <<'JAVA'
package com.suhas.nsedeliverymomentum;
import org.junit.Test;import static org.junit.Assert.*;
public class TargetMathTest {
 @Test public void longTargetIsAboveEntry(){double p=TargetMath.continuationPct(1.8,85);assertTrue(p>=1);assertTrue(TargetMath.longTarget(100,p)>100);}
 @Test public void shortTargetIsBelowEntry(){double p=TargetMath.shortPct(0.8,-1.0,-1.3,0.2,86);assertTrue(p>=1);assertTrue(TargetMath.shortTarget(100,p)<100);}
 @Test public void exampleDirectionIsCorrect(){assertEquals(110.0,TargetMath.longTarget(100,10),0.001);assertEquals(90.0,TargetMath.shortTarget(100,10),0.001);}
}
JAVA
cat > RELEASE-NOTES-v1.8.0.txt <<'TXT'
NSE Intraday Momentum v1.8.0 — CONFIRMED ENTRY / TARGET ALERTS

- All three engines are explicitly INTRADAY.
- Engine 1: continuation LONG.
- Engine 2: persistent-climb LONG.
- Engine 3: falling-knife / breakdown SHORT.
- Confirmed signals generate high-priority Android notifications with side, symbol, ENTRY price, directional TARGET price, target percentage, score and confidence.
- LONG target is above entry; SHORT target is below entry.
- Android 13+ notification permission is requested on app startup.
- Signal alert channel uses HIGH importance and vibration.
- v1.8.0 is notification/manual-execution only: the old CNC auto-buy path is no longer called.
- NIGHT LAB learning and v1.7 bounded-storage housekeeping remain intact.
- Targets are model objectives, not guaranteed fills or profits.
TXT
cd ..
mv nse-delivery-v170 nse-intraday-v180
