(() => {
  'use strict';
  const API='http://127.0.0.1:8000';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const json=async path=>{const r=await fetch(`${API}${path}`);const d=await r.json();if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d};
  let strategies=[];
  function addStyles(){const s=document.createElement('style');s.textContent=`.p24-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.p24-kpi{background:#132236;border:1px solid #29445f;border-radius:13px;padding:14px}.p24-kpi small{display:block;color:#a9bdd0}.p24-kpi b{font-size:1.35rem}.p24-gate{padding:12px;border-radius:10px;margin:6px 0}.p24-pass{background:#102a25;border:1px solid #2f7664}.p24-fail{background:#351a22;border:1px solid #80384b}.p24-source{background:#132236;border-left:4px solid #62d6a8;padding:12px;margin:12px 0}.p24-equity{height:180px;display:flex;align-items:flex-end;gap:2px;border-bottom:1px solid #31506f}.p24-equity i{display:block;flex:1;background:#62d6a8;min-width:1px}.p24-strategy{background:#132236;border:1px solid #29445f;border-radius:13px;padding:14px}.p24-strategy small{display:block;color:#a9bdd0;line-height:1.4;margin-top:6px}`;document.head.appendChild(s)}
  function install(){const nav=document.querySelector('.nav'),main=document.querySelector('main');if(!nav||!main||document.getElementById('researchLab'))return;const b=document.createElement('button');b.dataset.section='researchLab';b.textContent='Research & Backtesting';const settings=nav.querySelector('[data-section="settings"]');settings?nav.insertBefore(b,settings):nav.appendChild(b);const sec=document.createElement('section');sec.id='researchLab';sec.className='section';sec.innerHTML=`<div class="topbar"><div><h1>Research & Backtesting Lab</h1><p>Groww-only historical testing, walk-forward validation, Monte Carlo risk, drawdown and edge monitoring.</p></div><div class="pills"><span>Groww data only</span><span>No mock prices</span><span>Out-of-sample</span><span>Approval gate</span></div></div><div class="card"><div class="form-grid"><div><label>NSE symbol</label><input id="p24Symbol" value="RELIANCE"></div><div><label>Strategy</label><select id="p24Strategy"></select></div><div><label>History</label><select id="p24Years"><option>5</option><option>7</option><option>10</option></select></div></div><div class="actions"><button id="p24Run">RUN FULL RESEARCH</button><button class="secondary" id="p24Backtest">BACKTEST ONLY</button></div><div class="p24-source"><b>Data boundary</b><br>Every result must come from Groww historical candles. Missing access returns DATA UNAVAILABLE; no sample result is fabricated.</div></div><div id="p24Output" class="card" style="margin-top:16px"><div class="muted">Choose a symbol and run research.</div></div><div class="card" style="margin-top:16px"><h3>Strategy library</h3><div id="p24Catalog" class="p24-grid"></div></div>`;main.appendChild(sec);b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));b.classList.add('active');sec.classList.add('active')};sec.querySelector('#p24Run').onclick=()=>run(true);sec.querySelector('#p24Backtest').onclick=()=>run(false)}
  function renderCatalog(){document.getElementById('p24Strategy').innerHTML=strategies.map(x=>`<option value="${esc(x.strategy_id)}">${esc(x.name)}</option>`).join('');document.getElementById('p24Catalog').innerHTML=strategies.map(x=>`<div class="p24-strategy"><b>${esc(x.name)}</b><small>${esc(x.description)}</small><small><b>Entry:</b> ${esc(x.entry_rules.join(' · '))}</small></div>`).join('')}
  function metrics(m){return `<div class="p24-grid"><div class="p24-kpi"><small>Total trades</small><b>${m.total_trades}</b></div><div class="p24-kpi"><small>Win rate</small><b>${Number(m.win_rate_pct).toFixed(1)}%</b></div><div class="p24-kpi"><small>Profit factor</small><b>${Number(m.profit_factor).toFixed(2)}</b></div><div class="p24-kpi"><small>CAGR</small><b>${Number(m.cagr_pct).toFixed(1)}%</b></div><div class="p24-kpi"><small>Sharpe</small><b>${Number(m.sharpe).toFixed(2)}</b></div><div class="p24-kpi"><small>Max drawdown</small><b>${Number(m.max_drawdown_pct).toFixed(1)}%</b></div></div>`}
  async function run(full){const symbol=document.getElementById('p24Symbol').value.trim().toUpperCase(),strategy=document.getElementById('p24Strategy').value,years=document.getElementById('p24Years').value,out=document.getElementById('p24Output');out.innerHTML='<div class="warn"><b>Loading real Groww candles…</b></div>';try{const d=await json(full?`/api/research/full-report/${encodeURIComponent(symbol)}/${strategy}?years=${years}`:`/api/research/backtest/${encodeURIComponent(symbol)}/${strategy}?years=${years}`);if(!full){out.innerHTML=`<h3>${esc(symbol)} · ${esc(d.strategy.name)}</h3><div class="p24-source">Source: ${esc(d.source_metadata.provider)} · ${d.candle_count} valid candles · costs included</div>${metrics(d.metrics)}`;return}const g=d.approval.gates;out.innerHTML=`<h3>${esc(symbol)} · Full research report</h3><div class="p24-source">Groww Trading API only · no mock market data</div>${metrics(d.backtest.metrics)}<h4>Walk-forward</h4><p>${d.walk_forward.summary.profitable_test_windows}/${d.walk_forward.summary.windows} profitable out-of-sample windows · ${Number(d.walk_forward.summary.out_of_sample_consistency_pct).toFixed(1)}%</p><h4>Monte Carlo</h4><div class="p24-grid"><div class="p24-kpi"><small>Probability of profit</small><b>${Number(d.monte_carlo.probability_of_profit_pct).toFixed(1)}%</b></div><div class="p24-kpi"><small>Probability ≥10% loss</small><b>${Number(d.monte_carlo.probability_of_10pct_loss_pct).toFixed(1)}%</b></div><div class="p24-kpi"><small>Probability ₹1 lakh</small><b>${Number(d.monte_carlo.probability_reach_1_lakh_pct).toFixed(4)}%</b></div></div><h4>Approval gate</h4>${Object.entries(g).map(([k,v])=>`<div class="p24-gate ${v?'p24-pass':'p24-fail'}"><b>${v?'PASS':'FAIL'}</b> · ${esc(k.replaceAll('_',' '))}</div>`).join('')}<div class="warn"><b>${d.approval.approved_for_paper_observation?'Eligible for paper observation':'Rejected for paper observation'}</b><br>${esc(d.approval.reason)}</div>`}catch(e){out.innerHTML=`<div class="warn"><b>DATA UNAVAILABLE</b><br>${esc(e.message)}<br>No mock or synthetic result was substituted.</div>`}}
  async function init(){addStyles();install();try{strategies=(await json('/api/research/strategies')).items||[];renderCatalog()}catch(e){}}
  const previous=document.createElement('script');previous.src='production23.js';previous.onload=init;previous.onerror=init;document.head.appendChild(previous);
})();
