plugins { id 'com.android.application' }

android {
    namespace 'com.suhas.multyfifastbuy'
    compileSdk 35

    defaultConfig {
        applicationId 'com.suhas.multyfifastbuy'
        minSdk 26
        targetSdk 29
        versionCode 100
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
