package com.suhas.research360engine;

import android.Manifest;
import android.annotation.SuppressLint;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.BroadcastReceiver;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.os.Build;
import android.os.Bundle;
import android.provider.Settings;
import android.text.InputType;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Switch;
import android.widget.TextView;
import android.widget.Toast;

import java.time.LocalTime;
import java.time.ZoneId;
import java.util.List;
import java.util.Locale;

public final class MainActivity extends Activity {
    private final int BG=Color.rgb(8,16,32),CARD=Color.rgb(17,29,52),ACCENT=Color.rgb(64,173,255),GREEN=Color.rgb(75,210,130),RED=Color.rgb(255,100,115),MUTED=Color.rgb(167,181,205),AMBER=Color.rgb(245,190,75);
    private TextView r360Confidence,ownConfidence,r360Maturity,ownMaturity,status,stats,logs,gate,connection,ipStatus,apiStatus,ownTop,sectorSummary,sectorConfidence,backupStatus;
    private LinearLayout r360Rows,sectorRows;private ScrollView mainScroll;private Switch armed,live;private EditText budget,limit,apiKey,totp,expectedIp;private android.os.Handler handler;private boolean internalToggle=false;private BroadcastReceiver receiver;private long lastIntentSignal=-1;

    @SuppressLint("UnspecifiedRegisterReceiverFlag")
    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);AppState.migrateV14(this,Db.get(this).rawNotificationCount());buildUi();requestNotifications();requestBackupStoragePermission();LearningBackup.autoRestoreIfFresh(this);startEngine();handler=new android.os.Handler(getMainLooper());handler.post(refreshLoop);receiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){refresh();}};IntentFilter f=new IntentFilter(EngineService.ACTION_UI);if(Build.VERSION.SDK_INT>=33)registerReceiver(receiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(receiver,f);handleBuyIntent(getIntent());}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);handleBuyIntent(i);}
    @Override protected void onDestroy(){if(receiver!=null)try{unregisterReceiver(receiver);}catch(Exception ignored){}if(handler!=null)handler.removeCallbacksAndMessages(null);super.onDestroy();}

    private void buildUi(){
        mainScroll=new ScrollView(this);ScrollView scroll=mainScroll;scroll.setBackgroundColor(BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(36));scroll.setFillViewport(true);scroll.setSmoothScrollingEnabled(false);scroll.setFocusableInTouchMode(true);scroll.setDescendantFocusability(ViewGroup.FOCUS_BEFORE_DESCENDANTS);scroll.addView(root);scroll.requestFocus();
        root.addView(text("RESEARCH360 INTELLIGENCE",20,Color.WHITE,true));root.addView(text("v1.7 • LG G7 ThinQ • persistent learning • responsive manual BUY/recheck • positive-sector scanner",11,MUTED,false));space(root,10);

        LinearLayout confRow=new LinearLayout(this);confRow.setOrientation(LinearLayout.HORIZONTAL);LinearLayout left=miniCard(),right=miniCard();left.addView(text("R360 MODEL CONFIDENCE",10,MUTED,true));r360Confidence=text("0%",28,ACCENT,true);left.addView(r360Confidence);r360Maturity=text("data maturity 0%",10,MUTED,false);left.addView(r360Maturity);right.addView(text("OWN MODEL CONFIDENCE",10,MUTED,true));ownConfidence=text("0%",28,ACCENT,true);right.addView(ownConfidence);ownMaturity=text("data maturity 0%",10,MUTED,false);right.addView(ownMaturity);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-2,1);cp.setMargins(0,0,dp(5),0);confRow.addView(left,cp);cp=new LinearLayout.LayoutParams(0,-2,1);cp.setMargins(dp(5),0,0,0);confRow.addView(right,cp);root.addView(confRow);space(root,10);

        LinearLayout state=card(root);status=text("Starting…",15,Color.WHITE,true);state.addView(status);connection=text("Checking Groww API and static IP…",13,MUTED,true);state.addView(connection);gate=text("Evidence gates: collecting data",11,MUTED,false);state.addView(gate);state.addView(text("Confidence is calibrated from resolved shadow outcomes and can rise OR fall. Data maturity measures sample size separately, so the app does not fake confidence just because many callbacks arrived.",10,MUTED,false));space(root,10);

        LinearLayout controls=card(root);controls.addView(text("CONTROL",13,MUTED,true));armed=new Switch(this);armed.setText("ARM RESEARCH360 + MARKET LEARNING");armed.setTextColor(Color.WHITE);armed.setChecked(AppState.isArmed(this));controls.addView(armed);controls.addView(text("ARM ON captures only validated Research360 stock-call messages, learns in shadow mode, scans the independent market model and runs the isolated Groww sector engine.",10,MUTED,false));live=new Switch(this);live.setText("AUTONOMOUS LIVE ORDER PLACING");live.setTextColor(Color.WHITE);live.setChecked(AppState.liveOrders(this));controls.addView(live);controls.addView(text("Default OFF. This switch controls autonomous orders. A BUY button is a separate explicit one-time authorization and always asks for rupee amount + confirmation.",10,MUTED,false));
        armed.setOnCheckedChangeListener((v,on)->{if(internalToggle)return;AppState.setArmed(this,on);if(!on){AppState.setLiveOrders(this,false);internalToggle=true;live.setChecked(false);internalToggle=false;}else startEngine();refresh();});
        live.setOnCheckedChangeListener((v,on)->{if(internalToggle)return;if(!on){AppState.setLiveOrders(this,false);refresh();return;}internalToggle=true;live.setChecked(false);internalToggle=false;Db.Stats s=Db.get(this).stats();if(!AppState.isArmed(this)||!s.anyLiveGateReady()){dialog("Autonomous live remains locked","At least one isolated source needs ≥80% calibrated confidence, enough resolved shadow trades, positive net expectancy and the required win rate. Manual BUY remains available only on a current qualified recommendation.");return;}new Thread(()->{IpGuard.Status ips=new IpGuard(this).verifyNow();try{GrowwClient.Health h=new GrowwClient(this).validate(false);runOnUiThread(()->{refresh();if(!ips.verified||!h.ok){dialog("Live blocked","Groww API and the exact whitelisted public IP must both be verified.");return;}new AlertDialog.Builder(this).setTitle("Enable autonomous real orders?").setMessage("Groww API + static IP verified. This enables automatic orders only for evidence-ready model compartments. One live position at a time.").setNegativeButton("Cancel",null).setPositiveButton("ENABLE",(d,w)->{AppState.setLiveOrders(this,true);startEngine();refresh();}).show();});}catch(Exception e){runOnUiThread(()->dialog("Live blocked","Groww validation failed: "+shortMsg(e)));}}).start();});space(root,10);

        LinearLayout picks=card(root);picks.addView(text("RESEARCH360 PICKS — TODAY TOP 5",13,MUTED,true));picks.addView(text("Only validated stock-call notifications appear here. Research360 target/SL never controls our BUY decision or exit. BUY uses our revalidated price/score and asks for a rupee amount.",10,MUTED,false));r360Rows=new LinearLayout(this);r360Rows.setOrientation(LinearLayout.VERTICAL);picks.addView(r360Rows);space(root,10);

        LinearLayout next=card(root);next.addView(text("OWN MODEL — NEXT SESSION TOP 5",13,MUTED,true));next.addView(text("Independent NSE scan. Scores are calibrated/capped rather than letting many candidates saturate at 99%.",10,MUTED,false));ownTop=text("Scanner is building evidence…",11,Color.WHITE,false);next.addView(ownTop);space(root,10);

        LinearLayout sector=card(root);sector.addView(text("POSITIVE SECTORS — BEST 5 STOCKS",13,MUTED,true));sector.addView(text("Every Groww sector with a positive 1D price change is scanned. The app then ranks the five best executable stocks across the union of all green sectors. Sector learning remains isolated and persists across days.",10,MUTED,false));sectorConfidence=text("Sector confidence: 0% • maturity 0%",17,ACCENT,true);sector.addView(sectorConfidence);sectorSummary=text("Waiting for the all-positive-sector scan after market open…",11,MUTED,false);sector.addView(sectorSummary);sectorRows=new LinearLayout(this);sectorRows.setOrientation(LinearLayout.VERTICAL);sector.addView(sectorRows);space(root,10);

        LinearLayout risk=card(root);risk.addView(text("CAPITAL & RISK",13,MUTED,true));risk.addView(text("Trade budget (₹)",10,MUTED,true));budget=numberField("Budget ₹",String.format(Locale.US,"%.0f",AppState.budget(this)));risk.addView(budget);risk.addView(text("Daily loss ceiling (₹)",10,MUTED,true));limit=numberField("Daily loss limit ₹",String.format(Locale.US,"%.0f",AppState.dailyLossLimit(this)));risk.addView(limit);risk.addView(text("Default daily loss ceiling is ₹500. ₹100 NET after estimated brokerage/taxes/charges is the minimum successful-trade objective; the profit GTT and trailing engine use OUR realistic target, not Research360's target.",10,MUTED,false));Button saveRisk=button("SAVE BUDGET & LIMIT");risk.addView(saveRisk);saveRisk.setOnClickListener(v->{try{double bgt=Double.parseDouble(budget.getText().toString().trim()),lim=Double.parseDouble(limit.getText().toString().trim());if(bgt<=0||lim<=0)throw new Exception();AppState.setBudget(this,bgt);AppState.setDailyLossLimit(this,lim);Toast.makeText(this,"Budget and loss limit saved",Toast.LENGTH_SHORT).show();refresh();}catch(Exception e){Toast.makeText(this,"Enter positive numeric values",Toast.LENGTH_LONG).show();}});space(root,10);

        LinearLayout ip=card(root);ip.addView(text("STATIC-IP / SURFSHARK GUARD",13,MUTED,true));ip.addView(text("v1.7 re-verifies the actual public egress IP in the background even while autonomous live trading is OFF. Surfshark's VPN icon alone is not treated as proof.",10,MUTED,false));expectedIp=textField("Groww-whitelisted static public IP",false);expectedIp.setText(AppState.expectedStaticIp(this));ip.addView(expectedIp);ipStatus=text("Static IP not verified",11,MUTED,false);ip.addView(ipStatus);Button saveIp=button("SAVE WHITELISTED IP");ip.addView(saveIp);saveIp.setOnClickListener(v->{AppState.setExpectedStaticIp(this,expectedIp.getText().toString().trim());Toast.makeText(this,"Whitelisted IP saved",Toast.LENGTH_SHORT).show();startEngine();refresh();});Button verifyIp=button("VERIFY STATIC IP NOW");ip.addView(verifyIp);verifyIp.setOnClickListener(v->{verifyIp.setEnabled(false);new Thread(()->{IpGuard.Status s=new IpGuard(this).verifyNow();runOnUiThread(()->{verifyIp.setEnabled(true);Toast.makeText(this,s.summary(),Toast.LENGTH_LONG).show();refresh();});}).start();});Button surf=button("OPEN SURFSHARK");ip.addView(surf);surf.setOnClickListener(v->{if(!new IpGuard(this).openSurfshark())Toast.makeText(this,"Surfshark app not found",Toast.LENGTH_LONG).show();});space(root,10);

        LinearLayout grow=card(root);grow.addView(text("GROWW PAID API",13,MUTED,true));grow.addView(text("Dedicated API key/TOTP secret are saved once. The engine refreshes authentication automatically and periodically validates NSE CASH + paid live data.",10,MUTED,false));apiKey=textField("Groww API Key",false);totp=textField("Groww TOTP Secret",true);grow.addView(apiKey);grow.addView(totp);SecureStore ss=new SecureStore(this);if(!ss.get("api_key").isEmpty())apiKey.setHint("API Key saved — type only to replace");if(!ss.get("totp_secret").isEmpty())totp.setHint("TOTP secret saved — type only to replace");Button saveCred=button("SAVE / UPDATE API CREDENTIALS");grow.addView(saveCred);saveCred.setOnClickListener(v->{String k=apiKey.getText().toString().trim(),t=totp.getText().toString().trim();if(!k.isEmpty())ss.put("api_key",k);if(!t.isEmpty())ss.put("totp_secret",t);apiKey.setText("");totp.setText("");Toast.makeText(this,"Groww credentials saved",Toast.LENGTH_SHORT).show();startEngine();refresh();});apiStatus=text("Groww API not yet validated",11,MUTED,false);grow.addView(apiStatus);Button auth=button("REFRESH + AUTHENTICATE + FULL VALIDATION");grow.addView(auth);auth.setOnClickListener(v->{auth.setEnabled(false);new Thread(()->{String msg;try{GrowwClient.Health h=new GrowwClient(this).validate(true);msg=h.ok?"Groww CONNECTED — NSE CASH + live data validated":"Groww validation incomplete: "+h.message;}catch(Exception e){msg="Groww validation failed: "+shortMsg(e);}String m=msg;runOnUiThread(()->{auth.setEnabled(true);Toast.makeText(this,m,Toast.LENGTH_LONG).show();refresh();});}).start();});space(root,10);

        LinearLayout backup=card(root);backup.addView(text("PERSISTENT LEARNING BACKUP",13,MUTED,true));backup.addView(text("One rolling ZIP is kept in Downloads. It contains signals, market snapshots, shadow/live outcomes, sector learning, predictions and useful logs so the learning survives an uninstall. Groww API key, TOTP secret and access token are NEVER exported.",10,MUTED,false));backupStatus=text(LearningBackup.status(this),11,Color.WHITE,false);backup.addView(backupStatus);Button backupNow=button("BACKUP LEARNING NOW");backup.addView(backupNow);backupNow.setOnClickListener(v->{backupNow.setEnabled(false);new Thread(()->{LearningBackup.Result r=LearningBackup.backupNow(this,"MANUAL");runOnUiThread(()->{backupNow.setEnabled(true);Toast.makeText(this,r.message,Toast.LENGTH_LONG).show();refresh();});}).start();});Button restore=button("RESTORE LATEST BACKUP — EMPTY INSTALL ONLY");backup.addView(restore);restore.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Restore learning from Downloads?").setMessage("Restore is deliberately allowed only when this installation has no learning and no live trade. Existing/newer learning will never be overwritten. Groww credentials are not restored and must remain configured separately.").setNegativeButton("Cancel",null).setPositiveButton("RESTORE",(d,w)->{restore.setEnabled(false);new Thread(()->{LearningBackup.Result r=LearningBackup.restoreLatestIfFresh(this);runOnUiThread(()->{restore.setEnabled(true);Toast.makeText(this,r.message,Toast.LENGTH_LONG).show();refresh();});}).start();}).show());backup.addView(text("Automatic protection: a checkpoint is refreshed about every 15 minutes when learning changed, plus a final session backup after 15:35 IST. The same filename is replaced safely, so you only need to upload one file to ChatGPT.",10,MUTED,false));space(root,10);

        LinearLayout access=card(root);access.addView(text("DEVICE ACCESS",13,MUTED,true));Button notif=button("OPEN NOTIFICATION ACCESS");access.addView(notif);notif.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS)));Button battery=button("OPEN BATTERY OPTIMIZATION SETTINGS");access.addView(battery);battery.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS)));access.addView(text("v1.7 ignores generic Research360 app notifications and duplicate callbacks. Only meaningful stock BUY/CLOSE messages are persisted as Research360 observations.",10,MUTED,false));space(root,10);

        LinearLayout perf=card(root);perf.addView(text("LEARNING & PERFORMANCE",13,MUTED,true));stats=text("No validated observations yet",11,Color.WHITE,false);perf.addView(stats);space(root,10);LinearLayout lg=card(root);lg.addView(text("RECENT ENGINE LOG — LAST 8",13,MUTED,true));logs=text("Waiting for validated Research360 stock calls…",10,MUTED,false);logs.setTextIsSelectable(false);lg.addView(logs);setContentView(scroll);
    }

    private final Runnable refreshLoop=new Runnable(){@Override public void run(){refresh();handler.postDelayed(this,5000);}};
    private void refresh(){
        final int keepY=mainScroll==null?0:mainScroll.getScrollY();
        Db.Stats s=Db.get(this).stats();int rc=s.r360Confidence(),oc=s.ownConfidence(),sc=s.sectorConfidence();r360Confidence.setText(rc+"%");ownConfidence.setText(oc+"%");r360Maturity.setText("data maturity "+s.r360Maturity()+"%");ownMaturity.setText("data maturity "+s.ownMaturity()+"%");r360Confidence.setTextColor(rc>=80?GREEN:ACCENT);ownConfidence.setTextColor(oc>=80?GREEN:ACCENT);sectorConfidence.setText("Sector confidence: "+sc+"% • maturity "+s.sectorMaturity()+"%");sectorConfidence.setTextColor(sc>=80?GREEN:ACCENT);
        gate.setText(String.format(Locale.US,"R360: %s • %d shadow • %.1f%% ₹100-net wins • ₹%.0f net\nOwn: %s • %d shadow • %.1f%% wins • ₹%.0f net\nSector: %s • %d shadow • %.1f%% wins • ₹%.0f net",s.r360GateReady()?"READY":"LEARNING",s.r360ShadowTrades,s.r360WinRate()*100,s.r360ShadowNet,s.ownGateReady()?"READY":"LEARNING",s.ownShadowTrades,s.ownWinRate()*100,s.ownShadowNet,s.sectorGateReady()?"READY":"LEARNING",s.sectorShadowTrades,s.sectorWinRate()*100,s.sectorShadowNet));
        String mode=!AppState.isArmed(this)?"DISARMED":AppState.liveOrders(this)?"ARMED • AUTONOMOUS LIVE ENABLED":"ARMED • LEARNING / SHADOW • AUTONOMOUS LIVE OFF";status.setText(mode);status.setTextColor(AppState.liveOrders(this)?RED:(AppState.isArmed(this)?GREEN:MUTED));
        IpGuard g=new IpGuard(this);boolean ipOk=g.cachedVerified(180000),apiOk=AppState.apiHealthyFresh(this,10L*60L*1000L);connection.setText("GROWW API: "+(apiOk?"CONNECTED ✓":"CHECKING / NOT VALIDATED")+"   •   STATIC IP: "+(ipOk?"VERIFIED ✓":"NOT VERIFIED")+"\nSURFSHARK VPN: "+(g.vpnActive()?"ACTIVE":"NOT DETECTED")+"   •   NOTIFICATION ACCESS: "+(notificationAccess()?"ON":"OFF"));connection.setTextColor(apiOk&&ipOk?GREEN:(apiOk?AMBER:MUTED));
        long ah=AppState.apiHealthAt(this),aa=AppState.apiAuthAt(this);apiStatus.setText("API: "+(AppState.apiHealthOk(this)?"CONNECTED ✓":"NOT VALID")+" • "+AppState.apiHealthMessage(this)+"\nUCC: "+(AppState.apiUccMasked(this).isEmpty()?"not validated":AppState.apiUccMasked(this))+" • auth "+age(aa)+" • validation "+age(ah)+" • failures "+AppState.apiFailures(this));apiStatus.setTextColor(AppState.apiHealthOk(this)?GREEN:MUTED);
        String exp=AppState.expectedStaticIp(this),cur=AppState.lastPublicIp(this);ipStatus.setText("Whitelisted: "+(exp.isEmpty()?"not set":exp)+"\nCurrent public IP: "+(cur.isEmpty()?"unknown":cur)+"\nStatus: "+(ipOk?"VERIFIED ✓ • checked "+age(AppState.ipVerifiedAt(this)):"NOT VERIFIED • automatic recheck every ~45s while armed"));ipStatus.setTextColor(ipOk?GREEN:AMBER);
        renderRecommendations(r360Rows,Db.get(this).todayR360Top5(),"Waiting for validated Research360 BUY calls…");ownTop.setText(formatOwn(Db.get(this).latestPredictions()));sectorSummary.setText(AppState.sectorSummary(this));renderRecommendations(sectorRows,Db.get(this).todaySectorTop5(),"No qualified stock across today's positive Groww sectors yet.");
        if(backupStatus!=null)backupStatus.setText(LearningBackup.status(this));stats.setText(String.format(Locale.US,"Validated R360 stock messages: %d\nParsed R360 signals: %d • resolved: %d\nR360 shadow: %d trades • %d ₹100-net wins • ₹%.2f\nOwn shadow: %d trades • %d wins • ₹%.2f\nSector shadow: %d trades • %d wins • ₹%.2f\nLive net today: ₹%.2f\nBudget: ₹%.0f • Daily loss ceiling: ₹%.0f\nLegacy raw callback spam is not counted as model evidence.",s.notifications,s.parsed,s.resolvedSignals,s.r360ShadowTrades,s.r360ShadowWins,s.r360ShadowNet,s.ownShadowTrades,s.ownShadowWins,s.ownShadowNet,s.sectorShadowTrades,s.sectorShadowWins,s.sectorShadowNet,s.liveNetToday,AppState.budget(this),AppState.dailyLossLimit(this)));String l=Db.get(this).recentLogs(8);logs.setText(l.isEmpty()?"Waiting for validated events…":l);internalToggle=true;armed.setChecked(AppState.isArmed(this));live.setChecked(AppState.liveOrders(this));internalToggle=false;if(mainScroll!=null&&!editingField()){final int restoreY=keepY;mainScroll.post(()->mainScroll.scrollTo(0,restoreY));}
    }

    private boolean editingField(){return getCurrentFocus() instanceof EditText;}

    private void renderRecommendations(LinearLayout box,List<Db.Recommendation> rows,String empty){
        box.removeAllViews();if(rows==null||rows.isEmpty()){box.addView(text(empty,11,MUTED,false));return;}int rank=1;
        for(Db.Recommendation r:rows){
            LinearLayout line=new LinearLayout(this);line.setOrientation(LinearLayout.HORIZONTAL);line.setPadding(0,dp(8),0,dp(8));
            LinearLayout left=new LinearLayout(this);left.setOrientation(LinearLayout.VERTICAL);
            String sector=(r.sector==null||r.sector.isEmpty())?"":(" • "+r.sector);
            TextView name=text((rank++)+". "+r.symbol,14,Color.WHITE,true);left.addView(name);
            TextView detail=text(String.format(Locale.US,"%.0f%% • %s%s • %s",r.score,pretty(r.category),sector,r.status),10,statusColor(r.status),false);left.addView(detail);
            LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);line.addView(left,lp);
            String label=actionLabel(r.status);Button b=smallButton(label);boolean active=!isLiveActive(r.status);b.setEnabled(active);b.setAlpha(active?1.0f:0.45f);
            if(active)b.setOnClickListener(v->openBuyDialog(r.id));line.addView(b,new LinearLayout.LayoutParams(dp(92),dp(46)));box.addView(line);
        }
    }
    private static boolean isLiveActive(String s){return s!=null&&s.contains("LIVE_ACTIVE");}
    private String actionLabel(String s){if(isLiveActive(s))return"ACTIVE";if(s==null)return"RECHECK";String x=s.toUpperCase(Locale.ROOT);if(x.contains("NEW")||x.contains("WATCH")||x.contains("SHADOW_ACTIVE"))return"BUY";return"RECHECK";}
    private int statusColor(String s){if(s==null)return MUTED;String x=s.toUpperCase(Locale.ROOT);if(x.contains("LIVE_ACTIVE"))return GREEN;if(x.contains("NEW")||x.contains("WATCH")||x.contains("SHADOW_ACTIVE"))return ACCENT;if(x.contains("REJECT")||x.contains("EXPIRED"))return AMBER;return MUTED;}

    private void handleBuyIntent(Intent i){if(i==null)return;long sid=i.getLongExtra(RecommendationNotifier.EXTRA_SIGNAL_ID,-1);if(sid<=0||sid==lastIntentSignal)return;lastIntentSignal=sid;if(handler!=null)handler.postDelayed(()->openBuyDialog(sid),350);i.removeExtra(RecommendationNotifier.EXTRA_SIGNAL_ID);}
    private void openBuyDialog(long signalId){
        Db.Signal s=Db.get(this).getSignal(signalId);if(s==null){dialog("Recommendation unavailable","This recommendation no longer exists in the local learning database.");return;}
        if(!marketOpen()){dialog("Market closed — no order sent",s.symbol+" can be rechecked during the NSE cash session. The button is working; v1.7 deliberately refuses to submit a manual BUY outside the live-market window.");return;}
        Toast.makeText(this,"Rechecking "+s.symbol+" with live Groww data…",Toast.LENGTH_SHORT).show();
        new Thread(()->{try{
            GrowwClient gw=new GrowwClient(this);GrowwClient.Health h=gw.validate(false);if(!h.ok)throw new IllegalStateException("Groww API not healthy: "+h.message);
            Db.MarketSnapshot q=gw.getQuote(s.symbol);StrategyEngine se=new StrategyEngine(this);double score=se.score(s,q);double threshold=se.qualifyThreshold(s);boolean entryOk=se.entryNearEnough(s,q.ltp);
            if(score<threshold||!entryOk){String why=String.format(Locale.US,"Current score %.0f%% (required %.0f%%) • LTP ₹%.2f • original entry ₹%.2f. %s",score,threshold,q.ltp,s.entry,entryOk?"Score is below the current gate.":"Price is outside the validated entry window.");runOnUiThread(()->dialog("Not buyable right now",why));return;}
            runOnUiThread(()->showAmountDialog(s,q,score));
        }catch(Exception e){runOnUiThread(()->dialog("BUY recheck failed",shortMsg(e)));}}).start();
    }
    private void showAmountDialog(Db.Signal s,Db.MarketSnapshot q,double score){
        double px=q.ask>0?q.ask:q.ltp;EditText amount=numberField("Amount ₹",String.format(Locale.US,"%.0f",Math.min(AppState.budget(this),10000)));LinearLayout wrap=new LinearLayout(this);wrap.setOrientation(LinearLayout.VERTICAL);wrap.setPadding(dp(18),0,dp(18),0);wrap.addView(text(String.format(Locale.US,"%s • our score %.0f%%\nOUR entry ~₹%.2f\nEnter rupee amount; quantity is calculated automatically.",s.symbol,score,px),12,Color.WHITE,false));wrap.addView(amount);
        AlertDialog a=new AlertDialog.Builder(this).setTitle("Manual BUY — "+s.symbol).setView(wrap).setNegativeButton("Cancel",null).setPositiveButton("PREVIEW",null).create();
        a.setOnShowListener(d->a.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{try{double amt=Double.parseDouble(amount.getText().toString().trim());if(amt<=0||amt>AppState.budget(this))throw new IllegalArgumentException("Amount must be >0 and within configured budget ₹"+String.format(Locale.US,"%.0f",AppState.budget(this)));StrategyEngine se=new StrategyEngine(this);int qty=se.quantityForAmount(amt,px);if(qty<=0)throw new IllegalArgumentException("Amount cannot buy one share");String product=se.product(s);if(!se.economicallyFeasible(px,qty,product,score))throw new IllegalArgumentException(String.format(Locale.US,"At this amount, ₹100 net needs about %.2f%%. Increase the amount or skip this trade.",se.requiredNet100MovePct(px,qty,product)));double target=se.realisticTarget(px,qty,product,score,q);a.dismiss();confirmManualBuy(s,amt,qty,px,target,score);}catch(Exception ex){amount.setError(ex.getMessage());}}));a.show();
    }
    private void confirmManualBuy(Db.Signal s,double amount,int qty,double indicated,double target,double score){new AlertDialog.Builder(this).setTitle("Place REAL Groww BUY?").setMessage(String.format(Locale.US,"%s\nAmount: ₹%.2f\nCalculated quantity: %d\nIndicative OUR entry: ₹%.2f\nIndicative OUR profit GTT: ₹%.2f\n\nBefore sending, v1.7 rechecks the score, Groww API and exact static IP. Research360 target is ignored. Any unfilled LIMIT remainder is cancelled.",s.symbol,amount,qty,indicated,target)).setNegativeButton("Cancel",null).setPositiveButton("BUY NOW",(d,w)->executeManualBuy(s.id,amount)).show();}
    private void executeManualBuy(long signalId,double amount){Toast.makeText(this,"Final validation + order placement…",Toast.LENGTH_SHORT).show();new Thread(()->{String msg;boolean ok=false;try{if(!marketOpen())throw new IllegalStateException("Market is closed; no order sent");Db.Signal s=Db.get(this).getSignal(signalId);if(s==null)throw new IllegalStateException("Signal missing");Db.Stats st=Db.get(this).stats();if(st.liveNetToday<=-AppState.dailyLossLimit(this))throw new IllegalStateException("Daily loss ceiling reached");if(Db.get(this).openLiveTrade()!=null)throw new IllegalStateException("A live strategy is already open; one position at a time");GrowwClient gw=new GrowwClient(this);GrowwClient.Health h=gw.validate(false);if(!h.ok)throw new IllegalStateException("Groww API is not healthy");IpGuard.Status ip=new IpGuard(this).verifyNow();if(!ip.verified)throw new IllegalStateException("Static IP mismatch: current "+(ip.publicIp.isEmpty()?"unknown":ip.publicIp));Db.MarketSnapshot q=gw.getQuote(s.symbol);StrategyEngine se=new StrategyEngine(this);double score=se.score(s,q);if(score<se.qualifyThreshold(s)||!se.entryNearEnough(s,q.ltp))throw new IllegalStateException("Price/score moved outside our BUY window");double entry=tick05(q.ask>0?q.ask:q.ltp);int requested=se.quantityForAmount(amount,entry);if(requested<=0)throw new IllegalStateException("Amount cannot buy one share");String product=se.product(s);if(!se.economicallyFeasible(entry,requested,product,score))throw new IllegalStateException("₹100-net objective is no longer realistic at this amount");GrowwClient.OrderResult r=gw.placeLimit(s.symbol,requested,product,"BUY",entry);ManualFill fill=awaitManualFill(gw,r.orderId);if(fill.qty<=0)throw new IllegalStateException("BUY did not fill; unfilled order cancelled");Db.get(this).abandonOpenShadowForSignal(s.id);long tid=Db.get(this).openTrade(s.id,s.symbol,s.category,"LIVE",fill.qty,fill.price,score,r.orderId);Db.get(this).setSignalStatus(s.id,"LIVE_ACTIVE");double ourTarget=se.realisticTarget(fill.price,fill.qty,product,score,q);try{GrowwClient.SmartOrderResult g=gw.placeGttSell(s.symbol,fill.qty,product,ourTarget);AppState.setTradeGtt(this,tid,g.smartOrderId);Db.get(this).log("GTT",String.format(Locale.US,"Manual %s x%d • OUR profit GTT ₹%.2f",s.symbol,fill.qty,ourTarget));}catch(Exception ge){Db.get(this).log("GTT","Profit GTT failed for "+s.symbol+": "+shortMsg(ge)+" • engine trailing protection active");}Db.get(this).log("MANUAL-BUY",String.format(Locale.US,"%s x%d @ ₹%.2f • requested amount ₹%.0f • score %.0f",s.symbol,fill.qty,fill.price,amount,score));startEngine();msg=String.format(Locale.US,"BUY confirmed: %s x%d @ ~₹%.2f. Our exit engine is active.",s.symbol,fill.qty,fill.price);ok=true;}catch(Exception e){msg="BUY not placed: "+shortMsg(e);}String m=msg;boolean success=ok;runOnUiThread(()->{Toast.makeText(this,m,Toast.LENGTH_LONG).show();if(!success)dialog("Order not placed",m);refresh();});}).start();}
    private ManualFill awaitManualFill(GrowwClient gw,String orderId)throws Exception{ManualFill f=new ManualFill();GrowwClient.OrderDetail last=null;for(int i=0;i<12;i++){Thread.sleep(i==0?250:500);last=gw.getOrderDetail(orderId);if(last.filledQty>0){f.qty=last.filledQty;f.price=last.averageFillPrice;}if(last.remainingQty<=0&&last.filledQty>0)return f;if(isFailed(last.status))break;}if(last==null||last.remainingQty>0)try{gw.cancelOrder(orderId);}catch(Exception ignored){}if(f.qty>0&&f.price<=0){GrowwClient.OrderDetail d=gw.getOrderDetail(orderId);f.price=d.averageFillPrice;}return f;}
    private static boolean isFailed(String s){if(s==null)return false;String x=s.toUpperCase(Locale.ROOT);return x.contains("REJECT")||x.contains("CANCEL")||x.contains("FAIL");}private static double tick05(double p){return Math.ceil(p*20.0-1e-9)/20.0;}

    private String formatOwn(List<Db.Prediction> x){if(x==null||x.isEmpty())return"Full-market scanner has not produced a qualified top five yet.";StringBuilder b=new StringBuilder();for(Db.Prediction p:x)b.append(p.line()).append("\n\n");return b.toString().trim();}
    private static String pretty(String s){if("QUANT_INTRADAY".equals(s))return"Quant Intraday";if("MOST_INTRADAY_CASH".equals(s))return"MOST Intraday";if("MOST_OVERNIGHT".equals(s))return"MOST Overnight";if("SECTOR_MOMENTUM_INTRADAY".equals(s))return"Sector Momentum";return s==null?"":s;}
    private boolean notificationAccess(){String enabled=Settings.Secure.getString(getContentResolver(),"enabled_notification_listeners");String me=new ComponentName(this,ResearchNotificationListener.class).flattenToString();return enabled!=null&&enabled.contains(me);}private void startEngine(){if(!AppState.isArmed(this))return;Intent i=new Intent(this,EngineService.class);try{if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}catch(Exception e){Db.get(this).log("ERROR","Unable to start engine: "+shortMsg(e));}}private void requestNotifications(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},91);}
    private void requestBackupStoragePermission(){if(Build.VERSION.SDK_INT<29&&(checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.READ_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED))requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE,Manifest.permission.READ_EXTERNAL_STORAGE},92);}
    @Override public void onRequestPermissionsResult(int requestCode,String[] permissions,int[] grantResults){super.onRequestPermissionsResult(requestCode,permissions,grantResults);if(requestCode==92){boolean ok=true;for(int x:grantResults)if(x!=PackageManager.PERMISSION_GRANTED)ok=false;if(ok)new Thread(()->{LearningBackup.Result r=LearningBackup.autoRestoreIfFresh(this);runOnUiThread(()->{Toast.makeText(this,r.ok?r.message:"Downloads backup enabled",Toast.LENGTH_LONG).show();refresh();});}).start();else Toast.makeText(this,"Downloads permission is required to preserve learning across uninstall on this Android version",Toast.LENGTH_LONG).show();}}

    private boolean marketOpen(){LocalTime n=LocalTime.now(ZoneId.of("Asia/Kolkata"));return !n.isBefore(LocalTime.of(9,15))&&n.isBefore(LocalTime.of(15,20));}
    private void dialog(String title,String msg){new AlertDialog.Builder(this).setTitle(title).setMessage(msg).setPositiveButton("OK",null).show();}
    private LinearLayout card(LinearLayout root){LinearLayout x=miniCard();root.addView(x,new LinearLayout.LayoutParams(-1,-2));return x;}private LinearLayout miniCard(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(14),dp(14),dp(14),dp(14));android.graphics.drawable.GradientDrawable d=new android.graphics.drawable.GradientDrawable();d.setColor(CARD);d.setCornerRadius(dp(16));x.setBackground(d);return x;}private TextView text(String s,int sp,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(color);t.setPadding(0,dp(3),0,dp(3));if(bold)t.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);return t;}private EditText numberField(String hint,String value){EditText e=textField(hint,false);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setText(value);return e;}private EditText textField(String hint,boolean password){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(MUTED);e.setTextColor(Color.WHITE);e.setSingleLine(true);e.setBackgroundTintList(android.content.res.ColorStateList.valueOf(ACCENT));e.setPadding(0,dp(8),0,dp(8));if(password)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);return e;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setAllCaps(false);android.graphics.drawable.GradientDrawable d=new android.graphics.drawable.GradientDrawable();d.setColor(Color.rgb(35,110,210));d.setCornerRadius(dp(12));b.setBackground(d);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(48));p.setMargins(0,dp(8),0,0);b.setLayoutParams(p);return b;}private Button smallButton(String s){Button b=button(s);b.setTextSize(11);return b;}private void space(LinearLayout r,int d){View v=new View(this);r.addView(v,new LinearLayout.LayoutParams(1,dp(d)));}private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}private static String shortMsg(Exception e){String s=e.getMessage();return s==null?e.getClass().getSimpleName():s.substring(0,Math.min(300,s.length()));}private static String age(long t){if(t<=0)return"never";long sec=Math.max(0,(System.currentTimeMillis()-t)/1000);if(sec<60)return sec+"s ago";long m=sec/60;if(m<60)return m+"m ago";long h=m/60;return h<48?h+"h ago":(h/24)+"d ago";}
    private static final class ManualFill{int qty;double price;}
}
