package com.suhas.research360engine;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

public final class Db extends SQLiteOpenHelper {
    public static final int VERSION = 4;
    private static final ZoneId IST=ZoneId.of("Asia/Kolkata");
    private static Db instance;

    public static synchronized Db get(Context c) { if (instance == null) instance = new Db(c.getApplicationContext()); return instance; }
    private Db(Context c) { super(c, "research360_intelligence.db", null, VERSION); }

    @Override public void onCreate(SQLiteDatabase db) {
        createV1(db);createPredictions(db);
    }
    private void createV1(SQLiteDatabase db){
        db.execSQL("CREATE TABLE notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, ts INTEGER, package_name TEXT, app_label TEXT, title TEXT, text TEXT, raw TEXT, parsed INTEGER DEFAULT 0)");
        db.execSQL("CREATE TABLE signals (id INTEGER PRIMARY KEY AUTOINCREMENT, notification_id INTEGER, ts INTEGER, category TEXT, action TEXT, symbol TEXT, entry REAL, research_target REAL, research_stop REAL, reached REAL, status TEXT DEFAULT 'NEW', score REAL DEFAULT 0, first_ltp REAL DEFAULT 0, mfe REAL DEFAULT 0, mae REAL DEFAULT 0, close_seen INTEGER DEFAULT 0, last_update INTEGER DEFAULT 0)");
        db.execSQL("CREATE TABLE snapshots (id INTEGER PRIMARY KEY AUTOINCREMENT, signal_id INTEGER, ts INTEGER, ltp REAL, avg_price REAL, bid REAL, ask REAL, total_buy REAL, total_sell REAL, volume REAL, depth_imb REAL, spread_bps REAL, range_pos REAL, day_change REAL, score REAL)");
        db.execSQL("CREATE TABLE trades (id INTEGER PRIMARY KEY AUTOINCREMENT, signal_id INTEGER, symbol TEXT, category TEXT, mode TEXT, status TEXT, qty INTEGER, entry REAL, entry_ts INTEGER, peak REAL, exit_price REAL DEFAULT 0, exit_ts INTEGER DEFAULT 0, gross_pnl REAL DEFAULT 0, charges REAL DEFAULT 0, net_pnl REAL DEFAULT 0, exit_reason TEXT, score REAL DEFAULT 0, groww_order_id TEXT)");
        db.execSQL("CREATE TABLE logs (id INTEGER PRIMARY KEY AUTOINCREMENT, ts INTEGER, level TEXT, message TEXT)");
        db.execSQL("CREATE INDEX idx_signal_status ON signals(status)");db.execSQL("CREATE INDEX idx_trade_status ON trades(status)");db.execSQL("CREATE INDEX idx_signal_symbol ON signals(symbol)");
    }
    private void createPredictions(SQLiteDatabase db){
        db.execSQL("CREATE TABLE IF NOT EXISTS predictions (id INTEGER PRIMARY KEY AUTOINCREMENT, batch_key TEXT, created_ts INTEGER, phase TEXT, symbol TEXT, score REAL, rank_no INTEGER, reference_price REAL, detail TEXT, status TEXT DEFAULT 'PENDING', activated_signal_id INTEGER DEFAULT 0)");
        db.execSQL("CREATE INDEX IF NOT EXISTS idx_predictions_batch ON predictions(batch_key)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_predictions_status ON predictions(status)");
    }
    @Override public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) { if(oldVersion<2)createPredictions(db); }

    public long insertNotification(long ts, String pkg, String label, String title, String text, String raw, R360Parser.Parsed p) {
        SQLiteDatabase db = getWritableDatabase();ContentValues n = new ContentValues();n.put("ts", ts);n.put("package_name", pkg);n.put("app_label", label);n.put("title", title);n.put("text", text);n.put("raw", raw);n.put("parsed", p.parsed ? 1 : 0);long nid=db.insert("notifications",null,n);
        if(p.parsed){ContentValues s=new ContentValues();s.put("notification_id",nid);s.put("ts",ts);s.put("category",p.category);s.put("action",p.action);s.put("symbol",p.symbol);s.put("entry",p.entry);s.put("research_target",p.target);s.put("research_stop",p.stop);s.put("reached",p.reached);s.put("status","NEW");s.put("last_update",ts);long sid=db.insert("signals",null,s);if("CLOSE".equals(p.action)&&!p.symbol.isEmpty())markCloseSeen(p.symbol,ts);return sid;}return -1;
    }
    public long insertSyntheticSignal(String symbol,double entry,double modelScore,long predictionId){
        long sid=insertModelSignal("OWN_MODEL_INTRADAY",symbol,entry,modelScore);ContentValues p=new ContentValues();p.put("status","ACTIVATED");p.put("activated_signal_id",sid);getWritableDatabase().update("predictions",p,"id=?",new String[]{String.valueOf(predictionId)});return sid;
    }
    public long insertModelSignal(String category,String symbol,double entry,double modelScore){
        if(symbol==null||symbol.trim().isEmpty())return -1;ContentValues s=new ContentValues();long now=System.currentTimeMillis();s.put("notification_id",0);s.put("ts",now);s.put("category",category);s.put("action","BUY");s.put("symbol",symbol.trim().toUpperCase(Locale.ROOT));s.put("entry",entry);s.put("research_target",0);s.put("research_stop",0);s.put("reached",0);s.put("status","NEW");s.put("score",modelScore);s.put("first_ltp",entry);s.put("last_update",now);return getWritableDatabase().insert("signals",null,s);
    }
    public boolean hasRecentSignal(String category,String action,String symbol,double entry,long sinceTs){
        if(symbol==null||symbol.isEmpty())return false;Cursor c=getReadableDatabase().rawQuery("SELECT id FROM signals WHERE category=? AND action=? AND symbol=? AND ABS(entry-?)<0.011 AND ts>=? LIMIT 1",new String[]{category==null?"OTHER":category,action==null?"":action,symbol.toUpperCase(Locale.ROOT),String.valueOf(entry),String.valueOf(sinceTs)});try{return c.moveToFirst();}finally{c.close();}
    }

    public void markCloseSeen(String symbol,long ts){ContentValues v=new ContentValues();v.put("close_seen",1);v.put("last_update",ts);getWritableDatabase().update("signals",v,"symbol=? AND action='BUY' AND status IN ('NEW','WATCH','SHADOW_ACTIVE','LIVE_ACTIVE')",new String[]{symbol});}
    public void setSignalStatus(long id,String status){ContentValues v=new ContentValues();v.put("status",status);v.put("last_update",System.currentTimeMillis());getWritableDatabase().update("signals",v,"id=?",new String[]{String.valueOf(id)});}

    public CategoryStats categoryStats(String category){CategoryStats s=new CategoryStats();Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*),COALESCE(SUM(CASE WHEN net_pnl>=100 THEN 1 ELSE 0 END),0),COALESCE(AVG(net_pnl),0) FROM trades WHERE mode='SHADOW' AND status='CLOSED' AND category=?",new String[]{category==null?"OTHER":category});try{if(c.moveToFirst()){s.trades=c.getLong(0);s.wins=c.getLong(1);s.avgNet=c.getDouble(2);}}finally{c.close();}return s;}
    public static final class CategoryStats{public long trades,wins;public double avgNet;public double winRate(){return trades==0?0:(double)wins/trades;}}

    public List<Signal> activeSignals(){ArrayList<Signal> out=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT id,ts,category,action,symbol,entry,research_target,research_stop,reached,status,score,first_ltp,mfe,mae,close_seen,last_update FROM signals WHERE action='BUY' AND status IN ('NEW','WATCH','SHADOW_ACTIVE','LIVE_ACTIVE') ORDER BY last_update ASC LIMIT 250",null);try{while(c.moveToNext())out.add(Signal.from(c));}finally{c.close();}return out;}
    public Signal getSignal(long id){Cursor c=getReadableDatabase().rawQuery("SELECT id,ts,category,action,symbol,entry,research_target,research_stop,reached,status,score,first_ltp,mfe,mae,close_seen,last_update FROM signals WHERE id=?",new String[]{String.valueOf(id)});try{return c.moveToFirst()?Signal.from(c):null;}finally{c.close();}}
    public void updateSignal(long id,String status,double score,double firstLtp,double mfe,double mae){ContentValues v=new ContentValues();if(status!=null)v.put("status",status);v.put("score",score);if(firstLtp>0)v.put("first_ltp",firstLtp);v.put("mfe",mfe);v.put("mae",mae);v.put("last_update",System.currentTimeMillis());getWritableDatabase().update("signals",v,"id=?",new String[]{String.valueOf(id)});}
    public void insertSnapshot(long sid,MarketSnapshot q,double score){ContentValues v=new ContentValues();v.put("signal_id",sid);v.put("ts",q.ts);v.put("ltp",q.ltp);v.put("avg_price",q.averagePrice);v.put("bid",q.bid);v.put("ask",q.ask);v.put("total_buy",q.totalBuy);v.put("total_sell",q.totalSell);v.put("volume",q.volume);v.put("depth_imb",q.depthImbalance);v.put("spread_bps",q.spreadBps);v.put("range_pos",q.rangePosition);v.put("day_change",q.dayChangePct);v.put("score",score);getWritableDatabase().insert("snapshots",null,v);}

    public long openTrade(long signalId,String symbol,String category,String mode,int qty,double entry,double score,String orderId){ContentValues v=new ContentValues();v.put("signal_id",signalId);v.put("symbol",symbol);v.put("category",category);v.put("mode",mode);v.put("status","OPEN");v.put("qty",qty);v.put("entry",entry);v.put("entry_ts",System.currentTimeMillis());v.put("peak",entry);v.put("score",score);v.put("groww_order_id",orderId==null?"":orderId);return getWritableDatabase().insert("trades",null,v);}
    public Trade openTradeForSignal(long signalId){Cursor c=getReadableDatabase().rawQuery("SELECT id,signal_id,symbol,category,mode,status,qty,entry,entry_ts,peak,exit_price,exit_ts,gross_pnl,charges,net_pnl,exit_reason,score,groww_order_id FROM trades WHERE signal_id=? AND status='OPEN' ORDER BY id DESC LIMIT 1",new String[]{String.valueOf(signalId)});try{return c.moveToFirst()?Trade.from(c):null;}finally{c.close();}}
    public Trade openLiveTrade(){Cursor c=getReadableDatabase().rawQuery("SELECT id,signal_id,symbol,category,mode,status,qty,entry,entry_ts,peak,exit_price,exit_ts,gross_pnl,charges,net_pnl,exit_reason,score,groww_order_id FROM trades WHERE mode='LIVE' AND status='OPEN' ORDER BY id DESC LIMIT 1",null);try{return c.moveToFirst()?Trade.from(c):null;}finally{c.close();}}
    public void abandonOpenShadowForSignal(long signalId){ContentValues v=new ContentValues();v.put("status","CLOSED");v.put("mode","SHADOW_MANUAL_PROMOTED");v.put("exit_ts",System.currentTimeMillis());v.put("exit_reason","MANUAL_PROMOTION_TO_LIVE");getWritableDatabase().update("trades",v,"signal_id=? AND mode='SHADOW' AND status='OPEN'",new String[]{String.valueOf(signalId)});}
    public void purgeLegacyNotificationNoise(){SQLiteDatabase db=getWritableDatabase();db.delete("notifications","id NOT IN (SELECT notification_id FROM signals WHERE notification_id>0)",null);}
    public void updatePeak(long tradeId,double peak){ContentValues v=new ContentValues();v.put("peak",peak);getWritableDatabase().update("trades",v,"id=?",new String[]{String.valueOf(tradeId)});}
    public void closeTrade(long tradeId,double exit,double gross,double charges,double net,String reason){ContentValues v=new ContentValues();v.put("status","CLOSED");v.put("exit_price",exit);v.put("exit_ts",System.currentTimeMillis());v.put("gross_pnl",gross);v.put("charges",charges);v.put("net_pnl",net);v.put("exit_reason",reason);getWritableDatabase().update("trades",v,"id=?",new String[]{String.valueOf(tradeId)});Cursor c=getReadableDatabase().rawQuery("SELECT signal_id,category FROM trades WHERE id=?",new String[]{String.valueOf(tradeId)});try{if(c.moveToFirst()&&"OWN_MODEL_INTRADAY".equals(c.getString(1))){ContentValues p=new ContentValues();p.put("status","RESOLVED");getWritableDatabase().update("predictions",p,"activated_signal_id=?",new String[]{String.valueOf(c.getLong(0))});}}finally{c.close();}}

    public void savePredictions(String batchKey,String phase,List<Prediction> rows){SQLiteDatabase db=getWritableDatabase();db.beginTransaction();try{db.delete("predictions","batch_key=?",new String[]{batchKey});int rank=1;for(Prediction r:rows){ContentValues v=new ContentValues();v.put("batch_key",batchKey);v.put("created_ts",System.currentTimeMillis());v.put("phase",phase);v.put("symbol",r.symbol);v.put("score",r.score);v.put("rank_no",rank++);v.put("reference_price",r.referencePrice);v.put("detail",r.detail);v.put("status","PREMARKET".equals(phase)?"READY_TODAY":"PENDING_NEXT");db.insert("predictions",null,v);}db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public List<Prediction> latestPredictions(){ArrayList<Prediction> out=new ArrayList<>();Cursor k=getReadableDatabase().rawQuery("SELECT batch_key FROM predictions ORDER BY created_ts DESC LIMIT 1",null);String batch="";try{if(k.moveToFirst())batch=k.getString(0);}finally{k.close();}if(batch.isEmpty())return out;Cursor c=getReadableDatabase().rawQuery("SELECT id,batch_key,created_ts,phase,symbol,score,rank_no,reference_price,detail,status,activated_signal_id FROM predictions WHERE batch_key=? ORDER BY rank_no ASC LIMIT 5",new String[]{batch});try{while(c.moveToNext())out.add(Prediction.from(c));}finally{c.close();}return out;}
    public List<Prediction> readyPredictionsForActivation(){ArrayList<Prediction> out=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT id,batch_key,created_ts,phase,symbol,score,rank_no,reference_price,detail,status,activated_signal_id FROM predictions WHERE status='READY_TODAY' ORDER BY rank_no ASC LIMIT 5",null);try{while(c.moveToNext())out.add(Prediction.from(c));}finally{c.close();}if(!out.isEmpty())return out;long todayStart=LocalDate.now(IST).atStartOfDay(IST).toInstant().toEpochMilli();c=getReadableDatabase().rawQuery("SELECT id,batch_key,created_ts,phase,symbol,score,rank_no,reference_price,detail,status,activated_signal_id FROM predictions WHERE status='PENDING_NEXT' AND created_ts<? ORDER BY created_ts DESC,rank_no ASC LIMIT 5",new String[]{String.valueOf(todayStart)});try{while(c.moveToNext())out.add(Prediction.from(c));}finally{c.close();}return out;}
    public void markPredictionReadyToday(long id){ContentValues v=new ContentValues();v.put("status","READY_TODAY");getWritableDatabase().update("predictions",v,"id=?",new String[]{String.valueOf(id)});}

    public List<Recommendation> todayR360Top5(){long start=LocalDate.now(IST).atStartOfDay(IST).toInstant().toEpochMilli();ArrayList<Recommendation> out=new ArrayList<>();Set<String> seen=new HashSet<>();Cursor c=getReadableDatabase().rawQuery("SELECT id,symbol,category,score,status,entry,mfe,mae,ts FROM signals WHERE action='BUY' AND ts>=? AND category NOT IN ('OWN_MODEL_INTRADAY','SECTOR_MOMENTUM_INTRADAY') AND symbol!='' ORDER BY score DESC,ts DESC",new String[]{String.valueOf(start)});try{while(c.moveToNext()&&out.size()<5){String sym=c.getString(1);if(!seen.add(sym))continue;Recommendation r=new Recommendation();r.id=c.getLong(0);r.symbol=sym;r.category=c.getString(2);r.score=c.getDouble(3);r.status=c.getString(4);r.entry=c.getDouble(5);r.mfe=c.getDouble(6);r.mae=c.getDouble(7);out.add(r);}}finally{c.close();}return out;}
    public List<Recommendation> todaySectorTop3(){long start=LocalDate.now(IST).atStartOfDay(IST).toInstant().toEpochMilli();ArrayList<Recommendation> out=new ArrayList<>();Set<String> seen=new HashSet<>();Cursor c=getReadableDatabase().rawQuery("SELECT id,symbol,category,score,status,entry,mfe,mae,ts FROM signals WHERE action='BUY' AND ts>=? AND category='SECTOR_MOMENTUM_INTRADAY' AND symbol!='' ORDER BY score DESC,ts DESC",new String[]{String.valueOf(start)});try{while(c.moveToNext()&&out.size()<3){String sym=c.getString(1);if(!seen.add(sym))continue;Recommendation r=new Recommendation();r.id=c.getLong(0);r.symbol=sym;r.category=c.getString(2);r.score=c.getDouble(3);r.status=c.getString(4);r.entry=c.getDouble(5);r.mfe=c.getDouble(6);r.mae=c.getDouble(7);out.add(r);}}finally{c.close();}return out;}

    public PatternStats successfulR360Pattern(){PatternStats p=new PatternStats();Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*),COALESCE(AVG(sn.depth_imb),0),COALESCE(AVG(sn.spread_bps),0),COALESCE(AVG(sn.range_pos),0),COALESCE(AVG(sn.day_change),0) FROM snapshots sn JOIN signals sg ON sg.id=sn.signal_id JOIN trades t ON t.signal_id=sg.id WHERE t.mode='SHADOW' AND t.status='CLOSED' AND t.net_pnl>=100 AND sg.category NOT IN ('OWN_MODEL_INTRADAY','SECTOR_MOMENTUM_INTRADAY')",null);try{if(c.moveToFirst()){p.n=c.getLong(0);p.depth=c.getDouble(1);p.spread=c.getDouble(2);p.range=c.getDouble(3);p.dayChange=c.getDouble(4);}}finally{c.close();}return p;}

    public void log(String level,String msg){ContentValues v=new ContentValues();v.put("ts",System.currentTimeMillis());v.put("level",level);v.put("message",msg);getWritableDatabase().insert("logs",null,v);}
    public long rawNotificationCount(){return scalarLong(getReadableDatabase(),"SELECT COUNT(*) FROM notifications");}
    public Stats stats(){SQLiteDatabase db=getReadableDatabase();Stats s=new Stats();s.rawCallbacks=scalarLong(db,"SELECT COUNT(*) FROM notifications");s.notifications=scalarLong(db,"SELECT COUNT(*) FROM (SELECT 1 FROM signals WHERE notification_id>0 GROUP BY (ts/300000),category,action,symbol,ROUND(entry,2),ROUND(reached,2))");s.parsed=scalarLong(db,"SELECT COUNT(*) FROM signals WHERE notification_id>0");s.resolvedSignals=scalarLong(db,"SELECT COUNT(*) FROM signals WHERE action='BUY' AND category NOT IN ('OWN_MODEL_INTRADAY','SECTOR_MOMENTUM_INTRADAY') AND status IN ('DONE','REJECTED','EXPIRED','MANUAL_EXIT')");s.r360ShadowTrades=scalarLong(db,"SELECT COUNT(*) FROM trades WHERE mode='SHADOW' AND status='CLOSED' AND category NOT IN ('OWN_MODEL_INTRADAY','SECTOR_MOMENTUM_INTRADAY')");s.r360ShadowWins=scalarLong(db,"SELECT COUNT(*) FROM trades WHERE mode='SHADOW' AND status='CLOSED' AND category NOT IN ('OWN_MODEL_INTRADAY','SECTOR_MOMENTUM_INTRADAY') AND net_pnl>=100");s.r360ShadowNet=scalarDouble(db,"SELECT COALESCE(SUM(net_pnl),0) FROM trades WHERE mode='SHADOW' AND status='CLOSED' AND category NOT IN ('OWN_MODEL_INTRADAY','SECTOR_MOMENTUM_INTRADAY')");s.ownShadowTrades=scalarLong(db,"SELECT COUNT(*) FROM trades WHERE mode='SHADOW' AND status='CLOSED' AND category='OWN_MODEL_INTRADAY'");s.ownShadowWins=scalarLong(db,"SELECT COUNT(*) FROM trades WHERE mode='SHADOW' AND status='CLOSED' AND category='OWN_MODEL_INTRADAY' AND net_pnl>=100");s.ownShadowNet=scalarDouble(db,"SELECT COALESCE(SUM(net_pnl),0) FROM trades WHERE mode='SHADOW' AND status='CLOSED' AND category='OWN_MODEL_INTRADAY'");s.sectorShadowTrades=scalarLong(db,"SELECT COUNT(*) FROM trades WHERE mode='SHADOW' AND status='CLOSED' AND category='SECTOR_MOMENTUM_INTRADAY'");s.sectorShadowWins=scalarLong(db,"SELECT COUNT(*) FROM trades WHERE mode='SHADOW' AND status='CLOSED' AND category='SECTOR_MOMENTUM_INTRADAY' AND net_pnl>=100");s.sectorShadowNet=scalarDouble(db,"SELECT COALESCE(SUM(net_pnl),0) FROM trades WHERE mode='SHADOW' AND status='CLOSED' AND category='SECTOR_MOMENTUM_INTRADAY'");long day=LocalDate.now(IST).atStartOfDay(IST).toInstant().toEpochMilli();s.liveNetToday=scalarDouble(db,"SELECT COALESCE(SUM(net_pnl),0) FROM trades WHERE mode='LIVE' AND status='CLOSED' AND exit_ts>="+day);return s;}
    public String recentLogs(int limit){StringBuilder b=new StringBuilder();Cursor c=getReadableDatabase().rawQuery("SELECT level,message FROM logs WHERE message NOT LIKE '%Captured raw notification%' ORDER BY id DESC LIMIT ?",new String[]{String.valueOf(limit)});try{while(c.moveToNext())b.append(c.getString(0)).append(" • ").append(c.getString(1)).append("\n");}finally{c.close();}return b.toString();}
    private long scalarLong(SQLiteDatabase db,String sql){Cursor c=db.rawQuery(sql,null);try{return c.moveToFirst()?c.getLong(0):0;}finally{c.close();}}
    private double scalarDouble(SQLiteDatabase db,String sql){Cursor c=db.rawQuery(sql,null);try{return c.moveToFirst()?c.getDouble(0):0;}finally{c.close();}}

    public static final class Stats{
        public long rawCallbacks,notifications,parsed,resolvedSignals,r360ShadowTrades,r360ShadowWins,ownShadowTrades,ownShadowWins,sectorShadowTrades,sectorShadowWins;public double r360ShadowNet,ownShadowNet,sectorShadowNet,liveNetToday;
        public double r360WinRate(){return rate(r360ShadowTrades,r360ShadowWins);}public double ownWinRate(){return rate(ownShadowTrades,ownShadowWins);}public double sectorWinRate(){return rate(sectorShadowTrades,sectorShadowWins);}
        public int r360Confidence(){return confidence(r360ShadowTrades,r360ShadowWins,r360ShadowNet,resolvedSignals,14);}public int ownConfidence(){return confidence(ownShadowTrades,ownShadowWins,ownShadowNet,ownShadowTrades,12);}public int sectorConfidence(){return confidence(sectorShadowTrades,sectorShadowWins,sectorShadowNet,sectorShadowTrades,12);}
        public int r360Maturity(){return maturity(resolvedSignals+r360ShadowTrades*2,40);}public int ownMaturity(){return maturity(ownShadowTrades,18);}public int sectorMaturity(){return maturity(sectorShadowTrades,18);}
        public boolean r360GateReady(){return r360Confidence()>=80&&r360ShadowTrades>=14&&r360ShadowNet>0&&r360WinRate()>=.58;}public boolean ownGateReady(){return ownConfidence()>=80&&ownShadowTrades>=12&&ownShadowNet>0&&ownWinRate()>=.58;}public boolean sectorGateReady(){return sectorConfidence()>=80&&sectorShadowTrades>=12&&sectorShadowNet>0&&sectorWinRate()>=.58;}public boolean anyLiveGateReady(){return r360GateReady()||ownGateReady()||sectorGateReady();}
        private static double rate(long t,long w){return t==0?0:(double)w/t;}private static int maturity(long n,int target){return (int)Math.round(100*(1-Math.exp(-Math.max(0,n)/(double)Math.max(1,target))));}
        private static int confidence(long trades,long wins,double net,long evidence,int minGate){if(trades<=0)return 0;double wr=(wins+1.0)/(trades+2.0),avg=net/Math.max(1,trades),m=1.0-Math.exp(-(trades+Math.min(evidence,60)*.12)/9.0),quality=clamp((wr-.35)/.45,0,1),netQ=clamp((avg+90)/260.0,0,1);int c=(int)Math.round(100*(.38*m+.42*quality+.20*netQ));if(trades<4)c=Math.min(c,38);else if(trades<8)c=Math.min(c,58);if(trades<minGate)c=Math.min(c,79);return Math.max(0,Math.min(96,c));}
        private static double clamp(double x,double a,double b){return Math.max(a,Math.min(b,x));}
    }
    public static final class Signal{public long id,ts,lastUpdate;public String category,action,symbol,status;public double entry,target,stop,reached,score,firstLtp,mfe,mae;public boolean closeSeen;static Signal from(Cursor c){Signal s=new Signal();s.id=c.getLong(0);s.ts=c.getLong(1);s.category=c.getString(2);s.action=c.getString(3);s.symbol=c.getString(4);s.entry=c.getDouble(5);s.target=c.getDouble(6);s.stop=c.getDouble(7);s.reached=c.getDouble(8);s.status=c.getString(9);s.score=c.getDouble(10);s.firstLtp=c.getDouble(11);s.mfe=c.getDouble(12);s.mae=c.getDouble(13);s.closeSeen=c.getInt(14)!=0;s.lastUpdate=c.getLong(15);return s;}}
    public static final class Trade{public long id,signalId,entryTs,exitTs;public String symbol,category,mode,status,exitReason,orderId;public int qty;public double entry,peak,exitPrice,gross,charges,net,score;static Trade from(Cursor c){Trade t=new Trade();t.id=c.getLong(0);t.signalId=c.getLong(1);t.symbol=c.getString(2);t.category=c.getString(3);t.mode=c.getString(4);t.status=c.getString(5);t.qty=c.getInt(6);t.entry=c.getDouble(7);t.entryTs=c.getLong(8);t.peak=c.getDouble(9);t.exitPrice=c.getDouble(10);t.exitTs=c.getLong(11);t.gross=c.getDouble(12);t.charges=c.getDouble(13);t.net=c.getDouble(14);t.exitReason=c.getString(15);t.score=c.getDouble(16);t.orderId=c.getString(17);return t;}}
    public static final class MarketSnapshot{public long ts=System.currentTimeMillis();public double ltp,averagePrice,bid,ask,totalBuy,totalSell,volume,depthImbalance,spreadBps,rangePosition,dayChangePct,dayHigh,dayLow,marketCap,lastTradeQty,week52High,week52Low;}
    public static final class Recommendation{public long id;public String symbol="",category="",status="";public double score,entry,mfe,mae;public String line(int rank){return String.format(Locale.US,"%d. %s • %.0f%% • %s • %s",rank,symbol,score,pretty(category),status);}private static String pretty(String s){if("QUANT_INTRADAY".equals(s))return"Quant Intraday";if("MOST_INTRADAY_CASH".equals(s))return"MOST Intraday";if("MOST_OVERNIGHT".equals(s))return"MOST Overnight";if("SECTOR_MOMENTUM_INTRADAY".equals(s))return"Sector Momentum";return s;}}
    public static final class Prediction{public long id,createdTs,activatedSignalId;public String batchKey="",phase="",symbol="",detail="",status="";public double score,referencePrice;public int rank;static Prediction from(Cursor c){Prediction p=new Prediction();p.id=c.getLong(0);p.batchKey=c.getString(1);p.createdTs=c.getLong(2);p.phase=c.getString(3);p.symbol=c.getString(4);p.score=c.getDouble(5);p.rank=c.getInt(6);p.referencePrice=c.getDouble(7);p.detail=c.getString(8);p.status=c.getString(9);p.activatedSignalId=c.getLong(10);return p;}public String line(){return String.format(Locale.US,"%d. %s • %.0f%% • ₹%.2f%s",rank,symbol,score,referencePrice,detail==null||detail.isEmpty()?"":" • "+detail);}}
    public static final class PatternStats{public long n;public double depth,spread,range,dayChange;}
}
